### ISSUE TITLE
Upgrade to Alpakka Kafka 2.0

### ISSUE THREAD

**Issue by agemooij** [lightbend/cloudflow#100]
**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
This applies only to the Akka Streams runtime

**Describe the solution you'd like**
Upgrade our Alpakka Kafka dependency to the (soon to be released) 2.0 version to benefit from increased Kafka client performance and to enable #96

**Comment by RayRoestenburg** [comment]
See changes in docs here https://github.com/lightbend/cloudflow-docs/pull/20, once merged this issue is completed
