### ISSUE TITLE
Is Clustering Akka Streamlet still an experimental feature?

### ISSUE THREAD

**Issue by michael-read** [lightbend/cloudflow#1002]
**Is your feature request related to a problem? Please describe.**
Is Clustering Akka Streamlet still an experimental feature

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
Akka Streams

**Describe the solution you'd like**
Need docs and instructions on how to use in Java APIs.

**Additional context**
The Cloudflow docs mention an experimental feature of Akka Clustering which can be used within Cloudflow to build stateful Akka Streamlets. When will this be ready for prime time as it would allow us to greatly improve the complex Akka use cases?

**Comment by RayRoestenburg** [comment]
This is not experimental anymore, removed the comment in the docs.
