### ISSUE TITLE
`jobmanager.heap.size` gets overriden. Can't be set by the user.

### ISSUE THREAD

**Issue by franciscolopezsancho** [lightbend/cloudflow#1011]
**Describe the bug**
setting in conf file to a flink streamlet `jobmanager.heap.size` has not effect. Gets overriden

**To Reproduce**
adding `jobmanager.heap.size` to config and deploy
**Expected behavior**
see that value when `describe po` in FLINK_PROPERTIES

**Comment by andreaTP** [comment]
I will verify this bug, meanwhile, as a workaround, can you try to set the environment variable `FLINK_JM_HEAP`?

**Comment by franciscolopezsancho** [comment]
it works! @andreaTP. Thanks!

**Comment by RayRoestenburg** [comment]
💯
