### ISSUE TITLE
Problematic docker image name resolution in AppDescriptor for multi project builds

### ISSUE THREAD

**Issue by orElse** [lightbend/cloudflow#1012]
**Describe the bug**

https://github.com/lightbend/cloudflow/blob/master/core/sbt-cloudflow/src/main/scala/cloudflow/sbt/BuildAppPlugin.scala#L78

In a multi module project e.g.:
lib1
app1 dependsOn lib1
app2 dependsOn lib2

if lib1 contains streamlet implementations both the images descriptor for app1 & app2 inside the map will contain the information about the streamlet (class). 
When than e.g. app2 uses that streamlet (from lib1) in its blueprint - the used image in the actual descriptor for the app will depend on the ordering inside the map caching the classes to image names. So it can happen that in the descriptor of app2 a streamlet (coming from lib1) uses the image from app1. 

**To Reproduce**
Steps to reproduce the behavior. Please list down all steps on how to reproduce the bug. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by andreaTP** [comment]
@orElse are you able to provide a minimal repro?

**Comment by orElse** [comment]
I have to check to create a minimal reproducer - might take me a few days

**Comment by orElse** [comment]
reproducer at https://github.com/orElse/cloudflow-image-name

Caused by a probably not supported setup:
module containing the streamlet is only a CloudflowLibraryPlugin with manually added dependencies to CloudflowAkka

@andreaTP since I guess this is a not supported project setup the issue can probably be closed
