### ISSUE TITLE
Cloudflow: IntelliJ does not reflect references to class files generated for Avro schemas

### ISSUE THREAD

**Issue by grimlor** [lightbend/cloudflow#1016]
As presented in the Cloudflow/Akka Data Pipelines documentation, IntelliJ is not very intelligent about where to find the class files generated from Avro avsc files. I'd found where they are generated and @andreaTP validated that with the line of code referenced below:

https://github.com/lightbend/cloudflow/blob/484e34024a7e616a9ac786ffe47708795ef872d4/tools/cloudflow-sbt-plugin/src/main/scala/cloudflow/sbt/CommonSettingsAndTasksPlugin.scala#L99

As a workaround, he recommended adding the below to my `build.sbt`, which worked to make IntelliJ intelligent again.

`Compile / avroSpecificScalaSource := (Compile / sourceManaged).value`

**Comment by RayRoestenburg** [comment]
The schema code generator code in  CommonSettingsAndTasksPlugin.scala has been removed. This also removes the need for adding the avro code to a non-standard directory.
