### ISSUE TITLE
Executing example fails

### ISSUE THREAD

**Issue by aronayne** [lightbend/cloudflow#1029]
**Describe the bug**

I cloned the cloudflow repo to projects dir, copying the example build-akka-streamlets-java to a different dir and executing "sbt runLocal" results in error:

aronayne build-akka-streamlets-java $ sbt runLocal
[info] welcome to sbt 1.4.4 (Oracle Corporation Java 1.8.0_181)
[info] loading global plugins from /Users/aronayne/.sbt/1.0/plugins
[info] loading settings for project build-akka-streamlets-java-build-build from plugins.sbt ...
[info] loading project definition from /Users/aronayne/projects/build-akka-streamlets-java/project/project
java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)

Running "sbt runLocal" from the cloned repo: /projects/t2/cloudflow/examples/snippets/modules/ROOT/examples/build-akka-streamlets-java executes without error.

Is this the expected behaviour?  How to execute the examples in a separate dir?

**Expected behavior**
I expect there to be no difference in behavior in executing from /projects/build-akka-streamlets-java or /projects/t2/cloudflow/examples/snippets/modules/ROOT/examples/build-akka-streamlets-java

**Comment by andreaTP** [comment]
Hi @aronayne can you try to do the following after copying the folder:

 - remove the `project/project` directory: https://github.com/lightbend/cloudflow/tree/master/examples/snippets/modules/ROOT/examples/build-akka-streamlets-java/project/project
  - remove `project/plugins.sbt`: https://github.com/lightbend/cloudflow/blob/master/examples/snippets/modules/ROOT/examples/build-akka-streamlets-java/project/plugins.sbt
   - edit `plugins/cloudflow-plugins.sbt` removing everything but this line: addSbtPlugin("com.lightbend.cloudflow" % "sbt-cloudflow" % latestVersion) and substitute `latestVersion` with an actual Cloudflow release e.g. `"2.0.25"`

**Comment by aronayne** [comment]
thanks @andreaTP 

Here is my project structure after updates:

![image](https://user-images.githubusercontent.com/927254/114903304-92873f80-9e0e-11eb-9ce9-f6acb33e05e0.png)

new error:

aronayne build-akka-streamlets-java $ sbt clean runLocal
[info] welcome to sbt 1.4.4 (Oracle Corporation Java 1.8.0_181)
[info] loading global plugins from /Users/aronayne/.sbt/1.0/plugins
[info] loading project definition from /Users/aronayne/projects/build-akka-streamlets-java/project
/Users/aronayne/projects/build-akka-streamlets-java/build.sbt:21: error: not found: value CloudflowAkkaPlugin
    .enablePlugins(CloudflowAkkaPlugin)
                   ^
/Users/aronayne/projects/build-akka-streamlets-java/build.sbt:49: error: not found: value CloudflowApplicationPlugin
    .enablePlugins(CloudflowApplicationPlugin)
                   ^
/Users/aronayne/projects/build-akka-streamlets-java/build.sbt:59: error: not found: value CloudflowLibraryPlugin
  .enablePlugins(CloudflowLibraryPlugin)
                 ^
/Users/aronayne/projects/build-akka-streamlets-java/build.sbt:61: error: not found: value schemaCodeGenerator
    schemaCodeGenerator := SchemaCodeGenerator.Java,
    ^
/Users/aronayne/projects/build-akka-streamlets-java/build.sbt:61: error: not found: value SchemaCodeGenerator
    schemaCodeGenerator := SchemaCodeGenerator.Java,
                           ^
/Users/aronayne/projects/build-akka-streamlets-java/build.sbt:62: error: not found: value schemaPaths
    schemaPaths := Map(
    ^
/Users/aronayne/projects/build-akka-streamlets-java/build.sbt:63: error: not found: value SchemaFormat
      SchemaFormat.Avro -> "src/main/resources/avroschemas",
      ^
/Users/aronayne/projects/build-akka-streamlets-java/build.sbt:64: error: not found: value SchemaFormat
      SchemaFormat.Proto -> "src/main/resources/protobuf"
      ^
/Users/aronayne/projects/build-akka-streamlets-java/build.sbt:71: error: not found: value headerLicense
  headerLicense := Some(HeaderLicense.ALv2("(C) 2016-2020", "Lightbend Inc. <https://www.lightbend.com>")),
  ^
/Users/aronayne/projects/build-akka-streamlets-java/build.sbt:71: error: not found: value HeaderLicense
  headerLicense := Some(HeaderLicense.ALv2("(C) 2016-2020", "Lightbend Inc. <https://www.lightbend.com>")),
                        ^
/Users/aronayne/projects/build-akka-streamlets-java/build.sbt:94: error: not found: value schemaCodeGenerator
  schemaCodeGenerator := SchemaCodeGenerator.Java,
  ^
/Users/aronayne/projects/build-akka-streamlets-java/build.sbt:94: error: not found: value SchemaCodeGenerator
  schemaCodeGenerator := SchemaCodeGenerator.Java,
                         ^
sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)

________________________________________________________________________________________________________________________

Do I need to explicitly add CloudflowAkkaPlugin to build.sbt ?

________________________________________________________________________________________________________________________

build.sbt:

lazy val root =
  Project(id = "root", base = file("."))
    .aggregate(
      step0,
      step1,
      step2,
      step3,
      app,
      datamodel)

def appModule(moduleID: String): Project = {
  Project(id = moduleID, base = file(moduleID))
    .settings(
      name := moduleID
    )
    .withId(moduleID)
    .settings(commonSettings)
}

lazy val step0 = appModule("step0")
    .enablePlugins(CloudflowAkkaPlugin)
    .settings(
      Test / parallelExecution := false,
      Test / fork := true
    )

lazy val step1 = appModule("step1")
    .enablePlugins(CloudflowAkkaPlugin)
    .settings(
      Test / parallelExecution := false,
      Test / fork := true
    )

lazy val step2 = appModule("step2")
    .enablePlugins(CloudflowAkkaPlugin)
    .settings(
      Test / parallelExecution := false,
      Test / fork := true
    )

lazy val step3 = appModule("step3")
    .enablePlugins(CloudflowAkkaPlugin)
    .settings(
      Test / parallelExecution := false,
      Test / fork := true
    )

lazy val app = appModule("app")
    .enablePlugins(CloudflowApplicationPlugin)
    .settings(
      Test / parallelExecution := false,
      Test / fork := true
    )
    .dependsOn(step3)

// not used. Only to show avro configuration
//tag::avro-config[]
lazy val datamodel = (project in file("./my-cloudflow-library"))
  .enablePlugins(CloudflowLibraryPlugin)
  .settings(
    schemaCodeGenerator := SchemaCodeGenerator.Java,
    schemaPaths := Map(
      SchemaFormat.Avro -> "src/main/resources/avroschemas",
      SchemaFormat.Proto -> "src/main/resources/protobuf"
    )
  )
//end::avro-config[]

lazy val commonSettings = Seq(
  organization := "com.lightbend.cloudflow",
  headerLicense := Some(HeaderLicense.ALv2("(C) 2016-2020", "Lightbend Inc. <https://www.lightbend.com>")),
  scalaVersion := "2.12.11",
  javacOptions += "-Xlint:deprecation",
  scalacOptions ++= Seq(
    "-encoding", "UTF-8",
    "-target:jvm-1.8",
    "-Xlog-reflective-calls",
    "-Xlint",
    "-Ywarn-unused",
    "-Ywarn-unused-import",
    "-deprecation",
    "-feature",
    "-language:_",
    "-unchecked"
  ),

  scalacOptions in (Compile, console) --= Seq("-Ywarn-unused", "-Ywarn-unused-import"),
  scalacOptions in (Test, console) := (scalacOptions in (Compile, console)).value,

  libraryDependencies ++= Seq(
        "org.scalatest"          %% "scalatest"                 % "3.0.8"    % "test",
        "junit"                  % "junit"                      % "4.12"     % "test"),

  schemaCodeGenerator := SchemaCodeGenerator.Java,
  javacOptions ++= Seq("-Xlint:deprecation")
)

dynverSeparator in ThisBuild := "-"

**Comment by andreaTP** [comment]
content of `plugins/cloudflow-plugins.sbt` ?

**Comment by andreaTP** [comment]
sorry I see the mistake I  had a typo 🤦 
`plugins/cloudflow-plugins.sbt` should be instead `project/cloudflow-plugins.sbt`

sorry for the confusion.

**Comment by aronayne** [comment]
@andreaTP updated project structure:

![image](https://user-images.githubusercontent.com/927254/114904721-0d048f00-9e10-11eb-8e6d-1af47c0680c4.png)

re-executing:

aronayne build-akka-streamlets-java $ sbt clean runLocal
[info] welcome to sbt 1.4.4 (Oracle Corporation Java 1.8.0_181)
[info] loading global plugins from /Users/aronayne/.sbt/1.0/plugins
[info] loading settings for project build-akka-streamlets-java-build from cloudflow-plugins.sbt ...
[info] loading project definition from /Users/aronayne/projects/build-akka-streamlets-java/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
/Users/aronayne/projects/build-akka-streamlets-java/build.sbt:98: error: not found: value dynverSeparator
dynverSeparator in ThisBuild := "-"

returns error:

aronayne build-akka-streamlets-java $ sbt clean runLocal
[info] welcome to sbt 1.4.4 (Oracle Corporation Java 1.8.0_181)
[info] loading global plugins from /Users/aronayne/.sbt/1.0/plugins
[info] loading settings for project build-akka-streamlets-java-build from cloudflow-plugins.sbt ...
[info] loading project definition from /Users/aronayne/projects/build-akka-streamlets-java/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
/Users/aronayne/projects/build-akka-streamlets-java/build.sbt:98: error: not found: value dynverSeparator
dynverSeparator in ThisBuild := "-"

contents of cloudflow-plugins.sbt :

addSbtPlugin("com.lightbend.cloudflow" % "sbt-cloudflow" % "2.0.25")

I'm not sure if related but project/project dir is generated with following content when I execute "sbt clean runLocal":

![image](https://user-images.githubusercontent.com/927254/114904924-4937ef80-9e10-11eb-9c56-7794c5c718ba.png)

**Comment by andreaTP** [comment]
```
/Users/aronayne/projects/build-akka-streamlets-java/build.sbt:98: error: not found: value dynverSeparator
```
simply remove that line.

In Cloudflow we use `sbt-dynver` to track the version in the repository, it requires to have the project in a valid git repository.
If you want to run outside the Cloudflow working directory, you can simply remove dynver and its usages.

**Comment by aronayne** [comment]
Thank you! runLocal is working as expected now. The example throws UnsupportedOperationException but that's expected as it's thrown in src code:

public class ReportPrinter extends AkkaStreamlet {
  // 1. TODO Create inlets and outlets
  // 2. TODO Define the shape of the streamlet
  public StreamletShape shape() { throw new UnsupportedOperationException("Not Implemented"); }
  // 3. TODO Override createLogic to provide StreamletLogic
  public RunnableGraphStreamletLogic createLogic() { throw new UnsupportedOperationException("Not Implemented"); }
}
