### ISSUE TITLE
"sbtdocker.DockerBuildException: Could not parse Docker image id" caused by problem in sbt-docker 1.8.0 

### ISSUE THREAD

**Issue by leozilla** [lightbend/cloudflow#1032]
Edit: I found the bug in cloudflow 2.0.25 but haven't checked if its also an issue in earlier versions.

**Describe the bug**
`"se.marcuslonnberg" % "sbt-docker"          % "1.8.0"` has problems detecting correctly built docker images.
This is caused by the regex which is used to check the docker command output.

See: https://github.com/marcuslonnberg/sbt-docker/pull/120

**To Reproduce**
Run `sbt buildApp` (a couple of times) on a machine with little CPU resources.
So this ia timing/concurrency/load related. 

It also only happened to my on my Macbook pro but not on my Linux desktop machine (which is about 10x more powerful)

**Expected behavior**
`sbt buildApp` does not fail when docker images are correctly built

**Example**

Notice that the end of the line is not consistent.
```
[info] #10 writing image sha256:1cac6f2b79f612ce8f0c98b3b06a8c39a764e71b5355c941768143da6c64873c done
[info] #10 writing image sha256:ddcdba4032dcfc45ea5d21ca71658ca7c8f8cf14b5c890dc96f8ce566abc5bf9 0.0s done
[info] #10 writing image sha256:ed82a3329f8d4ee38bd15706fa98c1365e8246be44eae3e9899cf7e9dac98cc6
[info] #10 writing image sha256:b76bdf74a7ea47cbe14293193c0629737d5bdc7c39095a28d374ee025220c462 done
```

`sbt-docker 1.8.0` uses regex `.* writing image sha256:([0-9a-f]+) done$`
`sbt-docker 1.8.2` uses regex `.* writing image sha256:([0-9a-f]+) .*\\bdone$`

**Additional context**
The fix is pretty easy, just uprade sbt-docker plugin to 1.8.2

**Comment by leozilla** [comment]
btw: I can provide a PR for it if u like

**Comment by RayRoestenburg** [comment]
Hi @leozilla , thanks for reporting the bug! We love PR's 👍

**Comment by andreaTP** [comment]
Included here:
https://github.com/lightbend/cloudflow/pull/1031/files#diff-1382fcc041fee9420dbf7bd3a18566c0d77155c45a6061af516a9be751b6b1dfR260

that we will very likely merge today.

**Comment by andreaTP** [comment]
Fixed in 2.
