### ISSUE TITLE
Testkit continuosly emits Completed msgs when using sinkRef

### ISSUE THREAD

**Issue by RayRoestenburg** [lightbend/cloudflow#1033]
**Describe the bug**
https://cloudflow.zulipchat.com/#narrow/stream/263236-cloudflow/topic/Testkit.20continuosly.20emits.20Completed.20msgs.20when.20using.20sinkRef/near/235645761

**Comment by thomasschoeftner** [comment]
I added a reproducer spec in my cloudflow fork:
https://github.com/thomasschoeftner/cloudflow/commit/47289fdc52753028145419208e5ec8fedb7c2a3f

The first spec is interesting for this issue, the 2nd spec tackles [Issue#1054](https://github.com/lightbend/cloudflow/issues/1054).
