### ISSUE TITLE
Flink 1.10.3 is not mirrored anymore

### ISSUE THREAD

**Issue by andreaTP** [lightbend/cloudflow#1042]
**Describe the bug**
The Flink tgz file is not accessible anymore through the Apache mirrors:
https://www.apache.org/dyn/closer.lua/flink/flink-1.10.3/flink-1.10.3-bin-scala_2.12.tgz

**To Reproduce**
`simple-flink` scripted test is failing and this fixes:
https://github.com/lightbend/cloudflow/pull/1041/commits/5f8acea4d4ced76570f90034ef89f9de6c3832db

**Expected behavior**
`simple-flink` should execute successfully

**Comment by Lockdain** [comment]
Would you please close the issue? It seems to be resolved.
