### ISSUE TITLE
Helm charts install the wrong Cloudflow operator code

### ISSUE THREAD

**Issue by skonto** [lightbend/cloudflow#105]
**Describe the bug**
On master branch helm charts use the 1.3.0 release tags for installing the cloudflow operator.
That creates bugs as we update master. Right now things fails with:
```
com.typesafe.config.ConfigException$Missing: application.conf @ jar:file:/app/lib/com.lightbend.cloudflow.cloudflow-operator-71-fa7ef6d-dirty.jar!/application.conf: 2: No configuration setting found for key 'cloudflow.platform.cluster-type'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
```

**To Reproduce**
Install cloudflow from master.

**Expected behavior**
Cloudflow operator should run without issues.

**Screenshots**
N/A

**Additional context**
This blocks #65

**Comment by damhau** [comment]
I've built a working image. If anybody want to use is: https://hub.docker.com/r/damienh/cloudflow-operator
Edit installer/common/shared.sh and change
export operatorImageName="damienh/cloudflow-operator"
export operatorImageTag="4-f6f86bf"

then run: helm delete cloudflow --purge --no-hooks

and restart the installer.
