### ISSUE TITLE
Docs are missing a step to install CF CRD to be able to install CF from helm charts since v2.2.2

### ISSUE THREAD

**Issue by codesurf42** [lightbend/cloudflow#1113]
**Describe the bug**
When following official docs from https://cloudflow.io/docs/dev/administration/installing-cloudflow.html
you cannot install successfully Cloudflow operator with helm.

The problem is that since v2.2.2 there is another step needed as mentioned in release notes:
```The helm charts for installing Cloudflow operator have been modified. The cluster-admin role is no longer required. Please make sure to install the Cloudflow Application CRD before using the helm charts.```

**To Reproduce**
Follow official docs on https://cloudflow.io/docs/dev/administration/installing-cloudflow.html (e.g. - new cluster on minikube or any other k8s env)

**Expected behavior**
Easy installation as promised by docs

**Additional context**
The missing CRD can be added by such step:
```kubectl create -f 'https://raw.githubusercontent.com/lightbend/cloudflow/main/core/cloudflow-crd/kubernetes/cloudflow-crd.yaml' -n cloudflow``` 
before proceeding with helm for cloudlow.

**Comment by RayRoestenburg** [comment]
dev docs removed.
