### ISSUE TITLE
The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition is no longer served as of v1.22.

### ISSUE THREAD

**Issue by scpcy** [lightbend/cloudflow#1199]
client
        .apiextensions()
        .v1beta1()
        .customResourceDefinitions()
        .withName(App.ResourceName)
        .get()

This line of code rendered the cloudflow-operator useless (crashloop) as of Kubernetes 1.22.

**Comment by scpcy** [comment]
@michael-read

**Comment by thomasschoeftner** [comment]
+1 We will also run into the same issue when moving to K8S 1.22 next month...
I don't think 2.3.1 has fixed that.

**Comment by thomasschoeftner** [comment]
come to think of it:
What would be the oldest K8S version still supported, if we got rid of `v1beta1`?

**Comment by thomasschoeftner** [comment]
I've tried getting rid of `v1beta1`, but I cannot really test it because I don't have an env to set it up quickly... :(
https://github.com/thomasschoeftner/cloudflow/tree/drop-v1beta1-crds-for-k8s-122-compliance

**Comment by scpcy** [comment]
the problem is not the CRDs is the operator.

**Comment by synchris** [comment]
> I've tried getting rid of `v1beta1`, but I cannot really test it locally because I don't have an env to set it up quickly... :( #1212

https://github.com/lightbend/cloudflow/pull/1213/files

**Comment by franciscolopezsancho** [comment]
fixed with https://github.com/lightbend/cloudflow/pull/1212
