### ISSUE TITLE
Support more recent versions of Kubernetes

### ISSUE THREAD

**Issue by sebastian-alfers** [lightbend/cloudflow#1226]
Currently we only support `1.21`. Make sure to support more recent versions.

**Comment by thomasschoeftner** [comment]
Is there more to do than moving the CRD from version `v1beta1` to `v1`?

There is already [issue 1199](https://github.com/lightbend/cloudflow/issues/1199) with [PR 1212](https://github.com/lightbend/cloudflow/pull/1212) waiting.
