### ISSUE TITLE
Problem deploying multiple Flink streamlets in one go

### ISSUE THREAD

**Issue by debasishg** [lightbend/cloudflow#161]
**Describe the bug**
* In an application with multiple Flink streamlets and Akka streamlets, _only_ one Flink streamlet gets deployed correctly. All Akka streamlets deploy fine. On doing an _undeploy_ followed by another _deploy_ does the fix and deploys _all_ streamlets correctly.

**To Reproduce**

Here's the situation that replicates the bug (as reported):

* A multi streamlet application - Flink + Akka 
* 2 Flink streamlets
* Akka streamlets deploy fine with `kubectl cloudflow deploy ..`
* During deploy using the cli, only 1 Flink streamlet deploys successfully. 
* In the operator log, the message is: `2020-03-02 15:28:06,817 INFO [ActorSystemImpl] - Executing update action for resource stock-market-app in namespace stock-market-app`. But no streamlet mentioned whereas all others are mentioned. As in, no status changes to MODIFIED/ADDED
* Undeploy and then re-deploy
* All streamlets get deployed successfully

**Expected behavior**
* All streamlets should deploy correctly in the first go.
 
**Screenshots**
* None

**Additional context**

**Comment by debasishg** [comment]
Tried to replicate the scenario by adding more flink streamlets to taxi-ride application. Could not replicate - deploys fine. 

@mrooding - can we have the operator log files when this problem occurred ?

**Comment by mrooding** [comment]
Hi @debasishg 

Please find the logs attached. Not sure if you saw my PM on Gitter but I'll just leave that here too:

I'm starting to think that it may have something to do with the flink operator which keeps erroring on the "deleting" phase

Somehow, I only see this output for the flink streamlet which fails, the other flink streamlet consistently works fine:
```
{"json":{"app_name":"stock-market-app-rfq-prediction-calculator","ns":"stock-market-app","phase":"Deleting"},"level":"warning","msg":"Failed to reconcile resource stock-market-app/stock-market-app-rfq-prediction-calculator: GetJobOverview call failed with status FAILED and message '': Get http://stock-market-app-rfq-prediction-calculator-014a2e45.stock-market-app:8081/jobs/88606551181e331e44ffb1d3c2268f66: dial tcp: lookup stock-market-app-rfq-prediction-calculator-014a2e45.stock-market-app on 10.19.240.10:53: no such host","ts":"2020-03-02T15:44:57Z"}
```

[flink-operator.log](https://github.com/lightbend/cloudflow/files/4298283/flink-operator.log)

[cloudflow-operator.log](https://github.com/lightbend/cloudflow/files/4298282/cloudflow-operator.log)

**Comment by debasishg** [comment]
Thanks @mrooding  - I will take a detailed look at the logs and get back.

**Comment by maasg** [comment]
@mrooding I have been trying to reproduce this bug on Cloudflow 1.3.1 and I don't observe any related issues. All Flink streamlets seem to deploy correctly.
![image](https://user-images.githubusercontent.com/874997/76619684-bc937180-652b-11ea-86d3-3a5ecfd38aaf.png)

Are you still observing this issue? If so, could you use `v1.3.1` and check? We have upgraded to Flink 1.10 and Flink Operator 0.8.2.

Maybe this issue is solved as a side-effect of that?

**Comment by olofwalker** [comment]
This seems to work on 1.3.1 so I will close this issue.
