### ISSUE TITLE
Undeploy command ignores invalid input

### ISSUE THREAD

**Issue by mrooding** [lightbend/cloudflow#166]
**Describe the bug**
A typo in the question of whether or not the user would like to remove PVCs and Kafka topics leads to undesired behaviour if the user tried to type 'yes'.

**To Reproduce**
Answer the question with something other than 'yes' or 'no'

**Expected behavior**
Request new input from the user which matches the 2 options

**Screenshots**
![image](https://user-images.githubusercontent.com/5998869/75918804-b121b580-5e5c-11ea-901a-b5e44edecfbe.png)

**Additional context**

**Comment by yuchaoran2011** [comment]
Closing this issue. In Cloudflow 1.3.1, we have changed to remove all dependent k8s resources (identified via owner references set on them) when an application is undeployed.
