### ISSUE TITLE
Watch support for kubectl cloudflow status

### ISSUE THREAD

**Issue by wjglerum** [lightbend/cloudflow#206]
It would be nice to have a watch option when checking the status of a cloudflow application. Just like when watching pods in Kubernetes with `kubectl get pods -w`. I would like to suggest an extension for the cloudflow kubectl plugin. 
```
kubectl cloudflow status my-app -w
```
This way we can easily monitor deployments and scaling of our streamlets inside cloudflow applications.

This is just my idea, let me know what you think!

**Comment by RayRoestenburg** [comment]
Sounds like a nice feature! I usually do  `watch -n 3 -d kubectl cloudflow status my-app` to get a similar result, but since get pods has it, it would be nice if `kubectl cloudflow status` has it too.

**Comment by wjglerum** [comment]
@RayRoestenburg using `watch` seems like a good alternative for now, thanks!

**Comment by RayRoestenburg** [comment]
Since there is a good alternative, will close this.
