### ISSUE TITLE
Access the Flink Web UI in local mode

### ISSUE THREAD

**Issue by wjglerum** [lightbend/cloudflow#208]
**Is your feature request related to a problem? Please describe.**
At the moment we can't use the Flink Web UI when we run a cloudflow application in local mode with `sbt runLocal`

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
Only in local mode, on kubernetes it does start the Flink Web UI.

**Describe the solution you'd like**
We would like to use the Flink Web UI when we run the cloudflow application in local mode, this can be useful for debugging and inspection. It could work roughly the same as the generated endpoints for Akka-http endpoints in Streamlets. Where each Streamlet opens up the next port.

**Describe alternatives you've considered**
I tried including the Flink Web UI in the classpath, however it still didn't expose the Flink Web UI locally.

**Additional context**
I found the same question on [Gitter](https://gitter.im/lightbend/cloudflow?at=5e2c863444c076313ce5bd25), but no real solution yet.

**Comment by Lockdain** [comment]
@wjglerum Hi! Can you please tell me how to access the Flink Web UI while running on Kubernetes?

**Comment by wjglerum** [comment]
There are 2 ways that we used:
- Port forward to my local machine
- Expose the service over an ingress

For both use cases, first find the service name of your flink job: `kubectl get svc -n <namespace>` You can use the port number 8081 as a hint.

Port forward: `kubectl port-forward service/<service_name> -n <namespace> 8081:8081` and access the web uit at http://localhost:8081

Ingress: use the service name to expose it over your ingress, for example with https://kubernetes.github.io/ingress-nginx/

**Comment by Lockdain** [comment]
@wjglerum 
Thanks for the detailed answer!

**Comment by blublinsky** [comment]
Modifying pr https://github.com/lightbend/cloudflow/pull/655 to incorporate this one as well
