### ISSUE TITLE
Add a lifecycle for streamlets

### ISSUE THREAD

**Issue by eloots** [lightbend/cloudflow#233]
**Is your feature request related to a problem? Please describe.**

When running a CloudFlow application in the Sandbox during development, it would be useful to have a lifecycle hook that is called when a streamlet is stop (i.e. when hitting "return" to stop the application which was started via `runLocal`. This hook can be used to safely close user application specific resources.

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**

This request is independent of the CloudFlow release. I've used 1.3.1 and 1.3.3

**Describe the solution you'd like**

Add a Streamlet method (similar to `postStop` in an Akka Actor) that is called when a Streamlet stops.

**Describe alternatives you've considered**

n/a

**Additional context**

**Comment by RayRoestenburg** [comment]
There is an onStop now, and work is in progress to make sure coordinated shutdown occurs, closing this issue.
