### ISSUE TITLE
Create skeleton projects for Java and Scala

### ISSUE THREAD

**Issue by jasoncarreira** [lightbend/cloudflow#235]
**Is your feature request related to a problem? Please describe.**
Getting started with CloudFlow is frustrating because there's no easy way to get started with a working project you can build on. 

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
All runtimes 

**Describe the solution you'd like**
I'd like to be able to start from a simple Java or Scala skeleton project all configured with builds, Docker files, Avro schemas, etc. that I can then modify to my requirements. 

**Describe alternatives you've considered**
I'm trying to extract a working project from the examples, but it's not the easiest.

**Additional context**

**Comment by osleonard** [comment]
You can check https://github.com/lightbend/cloudflow/tree/master/examples. examples include java & scala

**Comment by jasoncarreira** [comment]
Right, but I want a skeleton project to just start coding in

**Comment by maasg** [comment]
@jasoncarreira I implemented a Scala and a Java template that should be helpful as a starting point.
Could you have a look at https://github.com/lightbend/cloudflow/pull/244
Could you try it, if you have the opportunity?

**Comment by jasoncarreira** [comment]
@maasg I'll look when it's merged
