### ISSUE TITLE
Support Scala 2.13

### ISSUE THREAD

**Issue by maasg** [lightbend/cloudflow#239]
Would it be possible to support Scala 2.13? 
Spark is usually behind the curve in relation to the scala version.
It should be possible to use akka-streams (maybe flink?) from a scala v2.13 project. 
Maybe publish libs for the components that can use scala 2.13?

From: Matt Hicks on Slack.

**Comment by RayRoestenburg** [comment]
We can at least build operator and akka streams with Scala 2.13.

**Comment by andreaTP** [comment]
this has been done now.

**Comment by maasg** [comment]
Awesome!
