### ISSUE TITLE
The examples use the deprecated `withOffsetContext` API

### ISSUE THREAD

**Issue by maasg** [lightbend/cloudflow#247]
**Describe the bug**
Many examples in the current `master` show the use of `...WithOffsetContext()` API while these APIs have been deprecated.

**To Reproduce**
see:
./snippets/modules/ROOT/examples/akkastreams-scala/src/main/scala/cloudflow/akkastreamsdoc/RecordSumFlow.scala
./snippets/modules/ROOT/examples/akkastreams-scala/src/main/scala/com/example/MetricsEgress.scala
./taxi-ride/logger/src/main/scala/taxiride/logger/FarePerRideLogger.scala
...
and many more

**Expected behavior**
Use the current API `...withCommittableContext` API

**Additional context**
Thanks to @jasoncarreira for bringing the deprecation issue up in gitter.

**Comment by jasoncarreira** [comment]
Would be interested in how to do this one:
```
return new RunnableGraphStreamletLogic(getContext()) {
            public RunnableGraph<?> createRunnableGraph() {
                return Consumer.sourceWithOffsetContext(kafkaConsumerSettings, Subscriptions.topics(topic))
                        .map(consumerRecord -> {
                                    Transaction transaction = (Transaction) consumerRecord.value();
                                    return new TransactionRequest(transaction, windowMillis);
                                })
                        .log("TransactionIngress")
                        .to(getSinkWithOffsetContext(outlet));
            }
        };
```

**Comment by maasg** [comment]
@jasoncarreira In order to reproduce this, what issue/error do you have with that code?

**Comment by jasoncarreira** [comment]
getSinkWithOffsetContext() is deprecated and gets highlighted as an issue in Intellij

**Comment by maasg** [comment]
@jasoncarreira thanks. Yes, I'm addressing that issue while working on unifying the API. I'll put a PR up this week.
