### ISSUE TITLE
Implement CRD/CR conversions in the Installer

### ISSUE THREAD

**Issue by michaelpnash** [lightbend/cloudflow#305]
We just noticed that we had hardcoded the image path to the cloudflow operator in the installer, this makes it very hard to test installing development versions of the Cloudflow operator.

We would like to move the Cloudflow operator image path to the CR for greater flexibility in the future.

This will force us to implement versioning for the CRD. The way k8s implements CRD versioning is described in the following article.

https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/

**Comment by yuchaoran2011** [comment]
This is no longer a problem with the current operator-based installer. Closing.
