### ISSUE TITLE
Add support for Helm 3

### ISSUE THREAD

**Issue by mrooding** [lightbend/cloudflow#31]
**Is your feature request related to a problem? Please describe.**
Currently, the GKE installer relies on Helm 2. Since Helm 3, Tiller is no longer required and `helm init` no longer exists as a CLI command. I've already created a PR to include dependencies required to run the installer in #30
 
**Describe the solution you'd like**
Either offer support for both Helm 2 and 3 or migrate to 3 only. I'm willing to work on a PR but I'd first like to know which approach you prefer.

**Describe alternatives you've considered**
I haven't looked into how Helm is being used by Cloudflow extensively but if it's purely for templating then maybe switching to Kustomize is an option

**Comment by olofwalker** [comment]
@mrooding Thanks for taking the time to write this issue. Things are currently in the works when it comes to improving the installation of Cloudflow, making this issue redundant. I will close it for now.
