### ISSUE TITLE
Modularize the installer by making dependency installation optional

### ISSUE THREAD

**Issue by michaelpnash** [lightbend/cloudflow#354]
The user should be prompted about installing Spark, Flink and Strimzi operators and be able to skip one or all of them if they so choose.

**Comment by yuchaoran2011** [comment]
This is relevant to https://github.com/lightbend/cloudflow-internal-ops/issues/53. Westpac uses Azure Event Hub as their managed Kafka. So Strimzi is not useful for them. If installation of all the dependencies can be configured, things that are not used by Westpac won't get into their secured environment, meaning we don't have to worry about fixing security vulnerabilities in those images.
