### ISSUE TITLE
Add option for the configuring NFS server

### ISSUE THREAD

**Issue by maasg** [lightbend/cloudflow#36]
Migrated from: https://github.com/lightbend/cloudflow-installer/issues/6
Submitted by: https://github.com/dhillonr

While installing Cloudflow in a cluster using ./install-gke.sh their is a part where it installs NFS Server. It installs the server using a helm chart whose path is hardcoded.

**Comment by olofwalker** [comment]
Due to the new direction of the installer, we will close this issue.
