### ISSUE TITLE
Default config is not merged in as fallback in AkkaStreamlet with Clustering.

### ISSUE THREAD

**Issue by RayRoestenburg** [lightbend/cloudflow#360]
**Describe the bug**
Not all default configuration on the classpath is merged in the ActorSystem in an Akkastreamlet with Clustering.

**Expected behavior**
`ConfigFactory.load()` should be merged as the final fallback.

**Comment by nolangrace** [comment]
Is this just a problem with the just the AkkaStreamlet with Clustering or all AkkaStreamlets?  Maybe I am missing something but it looks like the final fallback for the cluster stuff is the same as the normal AkkaStreamlet

**Comment by RayRoestenburg** [comment]
Duplicate of https://github.com/lightbend/cloudflow/issues/357

**Comment by RayRoestenburg** [comment]
@nolangrace still need to investigate, looking deeper into the code, you would think this should already work as expected. Closing this ticket. (continue on #357)
