### ISSUE TITLE
Basic release support for docs

### ISSUE THREAD

**Issue by RayRoestenburg** [lightbend/cloudflow#369]
- add a release branch
- point the build to release branch
- publishing from release branch
This will allow us to update master docs without automatically releasing it.

**Comment by maasg** [comment]
closed with:
https://github.com/lightbend/cloudflow/pull/402
https://github.com/lightbend/cloudflow/pull/400
https://github.com/lightbend/cloudflow/pull/399
https://github.com/lightbend/cloudflow/pull/389
https://github.com/lightbend/cloudflow/pull/385
https://github.com/lightbend/cloudflow/pull/384
