### ISSUE TITLE
Cloudflow with Akka Actors Example

### ISSUE THREAD

**Issue by jasoncarreira** [lightbend/cloudflow#386]
**Is your feature request related to a problem? Please describe.**
I'd love to have an example of integrating Akka Typed Actors in an Akka Streamlet. 

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
All runtimes

**Describe the solution you'd like**
Here's a use case:

A stream is coming in and uses mapAsync to call "ask" on a pool of actors. The pool of actors create a persistent actor for each ask and perform several async operations on it then return a value gathered from the persistent actor and close down the persistent actor. 

**Describe alternatives you've considered**
Trying to make this work myself, and would love some samples

**Additional context**
none

**Comment by nolangrace** [comment]
The connected car cluster sharding example leverages Akka Actors and Sharding within an Akka Streamlet.  The example currently uses Classic actors but I will be updating it to Typed actors soon.
 
https://github.com/lightbend/cloudflow/tree/master/examples/connected-car-cluster-sharding

Is this what you were looking for?

**Comment by nolangrace** [comment]
The connected-car-cluster sharding example I mentioned above has been updated to use typed actors as of cloudflow 2.0.8.

**Comment by RayRoestenburg** [comment]
Since the example is updated to use typed, I'll close this issue.
