### ISSUE TITLE
Upgrade to Alpakka 2

### ISSUE THREAD

**Issue by RayRoestenburg** [lightbend/cloudflow#387]

**Comment by nolangrace** [comment]
Is there anything specific that is blocking this?  I am gonna start working on implementing the external sharding Kafka and it requires alpakka 2.0.3

**Comment by nolangrace** [comment]
Actually it looks like master has already been upgraded to alpakka 2.0.3.  I think we can close this issue

**Comment by RayRoestenburg** [comment]
That's right, it's upgraded to 2.0.3 already.
