### ISSUE TITLE
Getting started examples should use the existing services not port-forwarding to the pods directly

### ISSUE THREAD

**Issue by skonto** [lightbend/cloudflow#39]
**Describe the bug**
Currently in the getting started guide and the examples READMEs we do port-forwarding at the pods directly. This is not a solid approach since if a pod is restarted then its name will change and kubectl will not handle automatically this event.

**Expected behavior**
Use services created instead.

**Comment by RayRoestenburg** [comment]
We do this now.

https://cloudflow.io/docs/current/get-started/exercise-example.html#_push_data_to_the_application
