### ISSUE TITLE
Update Flink runtime to use Flink 1.11.0

### ISSUE THREAD

**Issue by yuchaoran2011** [lightbend/cloudflow#416]
**Is your feature request related to a problem? Please describe.**
We are currently on 1.10.0. Upgrade to https://flink.apache.org/news/2020/07/06/release-1.11.0.html

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
Only applies to Flink runtime.

**Describe the solution you'd like**
With the multi-image architecture, it should be fairly easy to upgrade Flink without touching other runtimes.

**Comment by yuchaoran2011** [comment]
Flink 1.10 has a critical security vulnerability caused by log4j. Flink 1.11 has fixed this problem.

**Comment by yuchaoran2011** [comment]
Putting this on hold. We have opted to build a custom version of Flink 1.10 that includes upgrade of log4j.

**Comment by RayRoestenburg** [comment]
With the installer becoming more modular this becomes an issue of the flink operator project.
