### ISSUE TITLE
Installation docs still refer to the cloudflow-installer repository

### ISSUE THREAD

**Issue by agemooij** [lightbend/cloudflow#46]
**Describe the bug**
The `setup-gke-cluster.adoc` page still refers to the `cloudflow-installer` repository, which we have now inlined into the main `cloudflow` repo

**To Reproduce**
Live page: https://cloudflow.io/docs/current/get-started/setup-gke-cluster.html
Source: https://github.com/lightbend/cloudflow-docs/blob/master/docs-source/docs/modules/get-started/pages/setup-gke-cluster.adoc

**Expected behavior**
All docs should refer to the correct source of the installation scripts

**Comment by olofwalker** [comment]
Fixed by https://github.com/lightbend/cloudflow-docs-internal/pull/31
