### ISSUE TITLE
Investigate a Handover$Closed Exception while running Flink streamlets with state values defined

### ISSUE THREAD

**Issue by Lockdain** [lightbend/cloudflow#496]
**Describe the bug**
There are periodical errors occur while trying to execute some Apache Flink streamlets using in-memory state backend (in the sandbox mode or at the OKD, doesn't matter). From the outside it seems that streamlet fails to start but there are no any errors in the logs given, except the following:

`org.apache.flink.streaming.connectors.kafka.internal.Handover$ClosedException: null at org.apache.flink.streaming.connectors.kafka.internal.Handover.close(Handover.java:182) ~[flink-connector-kafka_2.12-1.10.0.jar:1.10.0] at org.apache.flink.streaming.connectors.kafka.internal.KafkaFetcher.cancel(KafkaFetcher.java:175) ~[flink-connector-kafka_2.12-1.10.0.jar:1.10.0] at org.apache.flink.streaming.connectors.kafka.FlinkKafkaConsumerBase.cancel(FlinkKafkaConsumerBase.java:818) ~[flink-connector-kafka-base_2.12-1.10.0.jar:1.10.0] at org.apache.flink.streaming.api.operators.StreamSource.cancel(StreamSource.java:147) ~[flink-streaming-java_2.12-1.10.0.jar:1.10.0] at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:136) ~[flink-streaming-java_2.12-1.10.0.jar:1.10.0] at org.apache.flink.streaming.runtime.tasks.StreamTask.cancel(StreamTask.java:602) ~[flink-streaming-java_2.12-1.10.0.jar:1.10.0] at org.apache.flink.runtime.taskmanager.Task$TaskCanceler.run(Task.java:1355) ~[flink-runtime_2.12-1.10.0.jar:1.10.0] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`

It seems that almost any exception raised inside Flink Streamlets is subjected to be swallowed somewhere and wrapped in the mysterious `Handover$Close: null` NPE. It's incredibly hard to investigate actual reasons of almost any failure since the log carries no any valuable information considering exceptions.

**To Reproduce**
The error periodically occurs while trying to run any Cloudflow pipeline (`runLocal`/`cluster`) with Apache Flink streamlets that use stateful values. So please refer to [the repo](https://github.com/OBenner/cloudflow-flink-external-kafka-example) with a very basic example given (please see the branch named _fails_).

**Expected behavior**
The expected behavior is to handle the error in a way that preseves and saves the actual reason of the failure, not swallowing and wraps up the exception. It also seems that the issue can be related to Apache Flink rather than Cloudflow, but this point needs to be detailed.

**Screenshots**
There are no any screenshots available.

**Additional context**

**Comment by vimaleshJeyavelmani** [comment]
Facing same issue while adding FlinkKafkaProducer 

`  val dlqKafkaProducer = new FlinkKafkaProducer[AvroMessage](
          topicName,
          new MapperSerializer(topicName),
          properties,
          FlinkKafkaProducer.Semantic.EXACTLY_ONCE
        )

	messageDS.addSink(dlqKafkaProducer).name("message-sink")
`

**Comment by Lockdain** [comment]
> Facing same issue while adding FlinkKafkaProducer
> 
> ```
> val messageDS = new FlinkKafkaProducer[AvroMessage](
>           topicName,
>           new MapperSerializer(topicName),
>           properties,
>           FlinkKafkaProducer.Semantic.EXACTLY_ONCE
>         )
> 
> messageDS.addSink(dlqKafkaProducer).name("message-sink")
> ```

Hi,

After some researches we've found out that this possibly not an issue, rather some incorrectness in the `logback.xml` config.
Try to put this string in your `logback.xml`:

`<logger name="org.apache.flink.runtime.executiongraph" level="INFO"/>`

This would probably give you a clue to the reasons of the failure.

**Comment by Lockdain** [comment]
Seems that the reason hides behind the incorrect logging configuration. I'd rather tend to close the issue.
