### ISSUE TITLE
Update existing docs to align with Cloudflow 2.0 features and changes.

### ISSUE THREAD

**Issue by maasg** [lightbend/cloudflow#501]
Update the current documentation to avoid inconsistencies between the product and the docs.

**Comment by maasg** [comment]
Update of the home page: https://github.com/lightbend/cloudflow/pull/494

Update of docs landing pages: https://github.com/lightbend/cloudflow/pull/495

Update of getting started: https://github.com/lightbend/cloudflow/pull/500

Update of

**Comment by RayRoestenburg** [comment]
This is done now I think?
