### ISSUE TITLE
Create Cluster GKE script should check for Zone and Region setup

### ISSUE THREAD

**Issue by nolangrace** [lightbend/cloudflow#51]
**Describe the bug**
For whatever reason my gcloud local configuration did not have Zone or Region setup although the project did have a default Zone and region.  This resulted in the error below being thrown multiple times when trying to setup the GKE Cluster

ERROR: (gcloud.container.clusters.create) One of [--zone, --region] must be supplied: Please specify location.

**To Reproduce**
Run the commands below to clear local Zone and Region settings
> gcloud config unset compute/zone
> gcloud config unset compute/region

Then run the GKE Cluster Setup Comand
> ./create-cluster-gke.sh cloudflow-cluster

**Expected behavior**

I would expect that the create-cluster-gke.sh script would check if the Zone and Region local configs are set.  If they are not present the script should indicate what the problem is and print how to fix it.

**Additional context**

Adding the missing configs involves running the commands below to set the Zone and Region
> gcloud config set compute/zone ZONE
> gcloud config set compute/region REGION

**Comment by mrooding** [comment]
This can be closed after #64 right?

**Comment by yuchaoran2011** [comment]
@mrooding Sorry for not noticing your reminder until today. Closing it now.
