### ISSUE TITLE
Document working with multiple versions of kubectl-cloudflow

### ISSUE THREAD

**Issue by yuchaoran2011** [lightbend/cloudflow#523]
**Is your feature request related to a problem? Please describe.**
@blublinsky provided a feedback that it would be good to have multiple versions of kubectl-cloudflow on the PATH and not having to overwrite the old version with the new version. This can be conveniently done by directly referring to each executable. Something like:
```
./kubectl-cloudflow-2.0.0 deploy app my-app.json
```
```
./kubectl-cloudflow-1.3.3 deploy app lightbend/my-app-image:latest
```

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
N/A

**Describe the solution you'd like**
Document how to do it

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by RayRoestenburg** [comment]
We would prefer if users stick with the latest. They can rename executables as they like of course.
