### ISSUE TITLE
Add a command to kubectl cloudflow to setup a TLS secured ingress for streamlets.

### ISSUE THREAD

**Issue by RayRoestenburg** [lightbend/cloudflow#538]
The cloudflow operator creates a k8s service for the streamlet. To access it from the outside, the user will have to setup an ingress. We'll have to check if this is made easier on GCP. Looks like you can use this: https://cloud.google.com/kubernetes-engine/docs/concepts/ingress

**Comment by longmuir** [comment]
To make things easier, could we actually deploy an Ingress Controller as part of the marketplace installation? 

How would that compare to just telling people to just install it?
(open question - not insisting on one way or the other)

**Comment by RayRoestenburg** [comment]
After discussion, we decided to use GKE-Ingress, and to add a feature to kubectl cloudflow to add ingresses for streamlets (TLS).
