### ISSUE TITLE
Transitive dependencies are not properly resolved in local mode

### ISSUE THREAD

**Issue by maasg** [lightbend/cloudflow#54]
**Describe the bug**
Looks like that transitive dependencies are not being resolved properly when using `runLocal`.

**To Reproduce**
e.g "lib - depends on (d1,d2)" , "proj - depends on (lib)" won't work.
worked around:  "proj - depends on (lib, d1, d2)"

**Expected behavior**
Transitive dependencies should be resolved

**Additional context**
Reported by @blublinsky when developing model serving applications that depend on TensorFlow

**Comment by RayRoestenburg** [comment]
Is this still an issue with new local runner @maasg ?
