### ISSUE TITLE
Link in readme references wrong version of bootstrap script

### ISSUE THREAD

**Issue by nolangrace** [lightbend/cloudflow#551]
**Describe the bug**
On the installer/README.md there is a link on "bootstrap script" that downloads bootstrap-install-script-1.3.3.sh when it should link to bootstrap-install-script-2.0.0.sh

"Download and run the **bootstrap script** to deploy the installer and instantiate a cloudflow custom resource.:"

**Comment by yuchaoran2011** [comment]
Fixed in https://github.com/lightbend/cloudflow/commit/b74b051398614a4932d33502827f70bf44fdf765
