### ISSUE TITLE
Improve wording in kubectl cloudflow related to authentication with docker registry (image pull secrets)

### ISSUE THREAD

**Issue by RayRoestenburg** [lightbend/cloudflow#556]
Right now kubectl cloudflow can prompt for username password but it is not immediately clear why, and what this is for. It would be better if it would prompt with something like:
```
Please provide credentials for pulling images from eu.gcr.io/proj, 
which will be stored in an image pull secret, 
so that the application can be successfully deployed.

Username:
```

**Comment by olofwalker** [comment]
In addition, to clarify the text we should also add a flag `--no-container-registry-auth` makes the CLI skip asking for credentials.

Depending on your setup, you do not always have to provide credentials in order to access the container registry.
