### ISSUE TITLE
Address high security vulnerabilities in Spark operator image, JAR dependencies

### ISSUE THREAD

**Issue by yuchaoran2011** [lightbend/cloudflow#580]
~Might involve upgrading to a Go 1.14 base image and higher version of Alpine.~ <- This has been implemented and merged
in https://github.com/lightbend/spark-on-k8s-operator/tree/lightbend-2.4.5
There are 13  remaining high security issues in JAR dependencies, which will be harder to fix, since this is just what Spark is packaged with. (Jackson, Apache:xerces mostly but also Log4j, Apache:spark, Apache:thrift and Javaassist)

**Comment by yuchaoran2011** [comment]
The latest image lightbend/sparkoperator:2.0.6-cloudflow-spark-2.4.5-1.1.2-scala-2.12 has [13 high](https://lightbendcloudflow.jfrog.io/ui/packages/docker:%2F%2Fdocker-local%2Flightbend%2Fsparkoperator/2.0.6-cloudflow-spark-2.4.5-1.1.2-scala-2.12?activeTab=xrayData) security issues. These are likely tricky to deal with. We might just handle them by making the installer modular, so that a user who doesn't use Spark can skip installing Spark operator.

**Comment by RayRoestenburg** [comment]
With the installer becoming more modular, this becomes an issue that needs to be solved in the spark operator project. If users want to use Spark they will have to consider the existing vulnerabilities in Spark and the Spark operator.
