### ISSUE TITLE
sbt-cloudflow 2.0 yields dysfunctional IDE projects

### ISSUE THREAD

**Issue by thomasschoeftner** [lightbend/cloudflow#584]
**Describe the bug**
It seems that the `CloudflowLibraryPlugin` - the one to be used in sub-projects for generating Avro or Protobuf classes - does not set the `managedSourceDirectories` for the IDEs properly.
When importing to IDEA, no more Avro / Protobuf classes are found in the IDE and the IDE is effectively dysfunctional because 
model-classes cannot be referenced any more.
This seems to happen, because a recent upgrade of sbt-cloudflow moved the generated classes from the `src_managed` folder to dedicated output folders for Avro and Protobuf.

Adding these settings to the sub-project holding the Avros fixed things:
`    (managedSourceDirectories in Compile) += (avroSpecificScalaSource in Compile).value,`
`    (managedSourceDirectories in Compile) += (crossTarget in Compile).value / "scalapb",`

Shouldn't the `CloudflowLibraryPlugin` do this out-of-the-box?
Also this fix is particularly ugly, because for Protobuf sources, I had to hard-code the `scalapb` folder (see above) because there is no variable holding this path (as with Avro sources).

**To Reproduce**
Create a model-subproject containing Avro or Protobuf sources and use those classes from another sub-project.
Then import all to IDEA IntelliJ.
-> Generated classes will not be found.

**Expected behavior**
The IDE should find the generated sources after importing the sbt project without any manual extra work (which is not persistent anyway)

**Additional context**

**Comment by RayRoestenburg** [comment]
The issue is that both scalapb and avro generator want to overwrite the managedSourceDirectories, so we can't simply set it to this.

**Comment by RayRoestenburg** [comment]
I have verified that you can add the source directories in the project in Intellij: https://www.jetbrains.com/help/idea/content-roots.html#adding_content_root. This seems to solve the problem @thomasschoeftner .

**Comment by RayRoestenburg** [comment]
Can this be closed?

**Comment by thomasschoeftner** [comment]
ok. let's close it then

**Comment by thomasschoeftner** [comment]
just for documentation - these SBT setting help so that the IDE won't need manual configuration:
```
    Compile / managedSourceDirectories += (Compile / avroSpecificScalaSource).value,
    Compile / managedSourceDirectories += (Compile / crossTarget).value / "java_avro",
    Compile / managedSourceDirectories += (Compile / crossTarget).value / "scalapb",
```

**Comment by RayRoestenburg** [comment]
Interesting, I'm wondering if we can put these in the plugin, so users would never have to do that? Is there any other side effect from setting this? @raboof do you think this can have issues, and should grpc dir be added here as well maybe?

**Comment by raboof** [comment]
hmm, normally I'd think sbt/the IntelliJ IDEA Scala plugin should be able to figure this out on its own, not sure what could be going on here.

**Comment by RayRoestenburg** [comment]
It seems it is because we put stuff in sub-dirs under src_managed, but I'm not sure why it is not picked up.

**Comment by thomasschoeftner** [comment]
I may be wrong, but looking at the file system on my current build, it seems that folders `scala_avro` and `scalapb` are not in any specific directory for managed sources, but directly in `target/scala-2.12` ...
