### ISSUE TITLE
Spark build script stops when running make-distribution.sh

### ISSUE THREAD

**Issue by yuchaoran2011** [lightbend/cloudflow#595]
**Describe the bug**
The Spark build script will stop when generating the Spark distribution: https://github.com/lightbend/cloudflow/blob/v2.0.6-RC15/external/multi-base-images/spark/buildLightbendSpark.sh#L44 without reporting any errors.

**To Reproduce**
Run `buildLightbendSpark.sh`.

**Expected behavior**
It should proceed.

**Additional context**
If all the commands in the script are run manually one by one in the terminal, things just work. But when put together in a script, somehow it doesn't proceed further.

The last output by the script before it stops is:
```
+ MVN=/Users/ray/src/repo/cloudflow/external/multi-base-images/spark/spark/build/mvn
+ ((  7  ))
+ case $1 in
+ NAME=cloudflow-2.12
+ shift
+ shift
+ ((  5  ))
+ case $1 in
+ MAKE_TGZ=true
+ shift
+ ((  4  ))
+ case $1 in
+ break
+ '[' -z /java_home ']'
+ '[' -z /java_home ']'
++ command -v git
+ '[' /usr/local/bin/git ']'
++ git rev-parse --short HEAD
+ GITREV=13caccb52d
+ '[' '!' -z 13caccb52d ']'
+ GITREVSTRING=' (git revision 13caccb52d)'
+ unset GITREV
++ command -v /Users/ray/src/repo/cloudflow/external/multi-base-images/spark/spark/build/mvn
+ '[' '!' /Users/ray/src/repo/cloudflow/external/multi-base-images/spark/spark/build/mvn ']'
++ /Users/ray/src/repo/cloudflow/external/multi-base-images/spark/spark/build/mvn help:evaluate -Dexpression=project.version -Pscala-2.12 -Phadoop-2.7 -Pkubernetes -Phive
++ grep -v INFO
++ grep -v WARNING
++ tail -n 1
+ VERSION=
```

**Comment by RayRoestenburg** [comment]
We should not have to build our own version of Spark once 2.4.8 comes out: https://github.com/lightbend/cloudflow/issues/714
