### ISSUE TITLE
Support many Application projects in one sbt project

### ISSUE THREAD

**Issue by RayRoestenburg** [lightbend/cloudflow#597]
Currently it is only fully supported to have one CloudflowApplication in an sbt project.
If you try to add more than one project using the CloudflowApplicationPlugin, and try to `buildApp` all applications in the project, you get the following feedback:

`[error] You can only define one project as a Cloudflow Application in a multi-project sbt build.`
It should be possible to remove this constraint and allow many app.json files to be built.

**Comment by thomasschoeftner** [comment]
Thanks for the ticket!

It may not be a sustainable solution, but I did some experiments on this.
Slightly modifying `BuildAppPlugin` allows to execute 'buildApp' on a single sub-project which is a `CloudflowApplication`:
  - replaced `projectWithCloudflowBasePlugin.all(ScopeFilter(inAnyProject)).value.flatten`
  - with `projectWithCloudflowBasePlugin.all(ScopeFilter(inDependencies(ThisProject, transitive = true))).value.flatten`
looked promising.
`runLocal` also works

**Comment by thomasschoeftner** [comment]
here's the PR:
https://github.com/lightbend/cloudflow/pull/601
