### ISSUE TITLE
spark-webhook-certs secrets keeps alive after ./uninstall bootstrap 

### ISSUE THREAD

**Issue by franciscolopezsancho** [lightbend/cloudflow#598]
**Describe the bug**
When execute the script https://github.com/lightbend/cloudflow/blob/master/installer/uninstall.sh
the secret `spark-webhook-certs` keeps alive in the cluster

**To Reproduce**
install in gke executing:
https://github.com/lightbend/cloudflow/blob/master/installer/create-cluster-gke.sh
https://github.com/lightbend/cloudflow/blob/master/installer/install-nfs.sh
https://github.com/lightbend/cloudflow/releases/download/v2.0.5/bootstrap-install-script-2.0.5.sh  (with params 1 and 2, respectively)

and when all the pods are running or completed
https://github.com/lightbend/cloudflow/blob/master/installer/uninstall.sh

**Expected behavior**
kubectl -n cloudflow get secrets should only contain one secret. `default-token-[xyz]   kubernetes.io/service-account-token`

**Screenshots**
<img width="754" alt="Screenshot 2020-07-22 at 09 54 23" src="https://user-images.githubusercontent.com/1381621/88150197-61703a80-cc01-11ea-8bf4-e627791820e8.png">

**Additional context**
None

**Comment by yuchaoran2011** [comment]
This is caused by us not using the Helm chart (We use YAMLs in the chart but not the chart itself). In the chart, the secret is cleaned up via a Helm [hook](https://github.com/helm/charts/blob/master/incubator/sparkoperator/templates/webhook-cleanup-job.yaml). For us, the simple workaround is to just add a line to the uninstall script:
```
k -n cloudflow delete secret spark-webhook-certs
```

**Comment by yuchaoran2011** [comment]
I added 
```
kubectl delete ns cloudflow
```
to the uninstall script. This should remove the secret too.
