### ISSUE TITLE
Add an sbt task to print schema diagram from blueprint

### ISSUE THREAD

**Issue by yuchaoran2011** [lightbend/cloudflow#602]
**Is your feature request related to a problem? Please describe.**
From @orElse on Gitter:
> when execute runLocal, there is a very nice overview how the streamlets are wired together - is there also an sbt task to get this picture "statically" just from the blueprint?
It would be great to have this feature.

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
All runtimes.

**Describe the solution you'd like**
See the quite above.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by thomasschoeftner** [comment]
ok, I just pushed a pull request for this:
https://github.com/lightbend/cloudflow/pull/787

Honestly, I'm not sure my change will do the trick, as I could not test them yet.
But maybe this is a place to start this.

The `CloudflowLocalRunnerPlugin` should now expose a new task `printAppGraph` which should print the ASCII art.

**Comment by RayRoestenburg** [comment]
`sbt printAppGraph` works as expected.

**Comment by RayRoestenburg** [comment]
Thanks @thomasschoeftner !
