### ISSUE TITLE
cloudflow-operator crashes and cannot recover after topic name validation errors

### ISSUE THREAD

**Issue by thomasschoeftner** [lightbend/cloudflow#603]
**Describe the bug**
When deploying a Cloudflow application with invalid topic names in the blueprint - specifically when using `_` - the cloudflow-operator crashes and cannot recover until the corrupt application is undeployed.

**To Reproduce**
Create a new Cloudflow application or use a sample application and introduce an invalid topic name conaining underscores (`_`). Then deploy to the cloudflow cluster and watch the `cloudflow-operator` pod dying all over again.

**Expected behavior**
Either the blueprint validation already reports the blueprint as broken or the `cloudflow-operator` should return an error when calling `kubectl cloudflow deploy <application>`.
After trying to deploy an application with a broken blueprint, the `cloudflow-operator` should survive and stay reactive.

**Screenshots**
n/a

**Additional context**
tested with Cloudflow 2.0.5 on GKE 1.16

**Comment by RayRoestenburg** [comment]
FYI The `_` is actually allowed in a Kafka topic name, but it is not allowed in a configmap name, since it must follow DNS-1123:
```
Invalid value: "topic-taxifares_not_allowed": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character
```
