### ISSUE TITLE
Add project templates to bootstrap getting started 

### ISSUE THREAD

**Issue by maasg** [lightbend/cloudflow#61]
I would like to have project templates that can help me to bootstrap my project faster and avoid common pitfalls, like using the correct plugin, project structure, or sbt version.

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
Having one template per runtime would be really handy.

**Describe the solution you'd like**
Available templates.

**Comment by mrooding** [comment]
I wanted to experiment with some Cloudflow projects and took a bit of extra time to set up a giter8 scala generator: https://github.com/mrooding/cloudflow-scala.g8

I assume that you'd like to move this to Lightbend's GH group. Let me know what your thoughts are on using this as a base @maasg

**Comment by RayRoestenburg** [comment]
In the meantime we have added some very simple template projects here: https://github.com/lightbend/cloudflow/tree/master/examples/templates

**Comment by RayRoestenburg** [comment]
Looks like we forgot to get back to you @mrooding !
