### ISSUE TITLE
OutofMemory issue in cloudflow-operator using custom skuber version on akka 2.6.8

### ISSUE THREAD

**Issue by RayRoestenburg** [lightbend/cloudflow#610]

**Comment by RayRoestenburg** [comment]
Might decide to sidestep issue with OOM and stick with Akka 2.5.x (if this is related) but include the fixes for vulnerabilities.

**Comment by raboof** [comment]
An existing theory was that this might have to do with the error handling while watching.

I created a test (https://github.com/michael-read/skuber/compare/mread-upgrade-to-akka-2.6.x...raboof:reproduce-memory-leak?expand=1) that seems to confirm this: after running the test (while it's sleeping), even after performing GC there are 5 PoolGateway instances on the heap.

It doesn't seem obvious that this was different on Akka 2.5 though yet, will test that next.

**Comment by raboof** [comment]
> It doesn't seem obvious that this was different on Akka 2.5 though yet, will test that next.

(I also see the same problem on 2.5)

**Comment by raboof** [comment]
> even after performing GC there are 5 PoolGateway instances on the heap.

Looking closer, I think those gateways/pools would have eventually (after the idle time-out) have been cleaned up - but perhaps they did not get cleaned up fast enough in this case.

A good improvement might be to make sure connection pools are reused across streams that share the same HTTPS configuration. Proposed upstream in https://github.com/doriordan/skuber/pull/317 .

**Comment by RayRoestenburg** [comment]
After more investigation it looks like the operator is stable (forcing GC shows the memory getting collected), it is possible it needs some more memory when many apps are kept running. Also at the time some important JAVA_OPTS where missing. It is possible that some error condition in the operator can cause more memory issues, but some safety measures have been taken. Closing this issue for now, though we will keep an eye on it.
