### ISSUE TITLE
TLS mode for Strimzi Kafka

### ISSUE THREAD

**Issue by jenoOvchi** [lightbend/cloudflow#616]
Hello!
Whats about support of TLS mode for Strimzi Kafka? Is it possible to configure it for Cloudflow?

**Comment by olofwalker** [comment]
@jenoOvchi 

It should be possible, all the tools needed are in place in Cloudflow 2.0.

There are several steps involved in doing this.

### 1. Modifying your current Kafka cluster using Strimzi

The Kafka cluster is created by Strimzi reading a `Kafka` CR that is created by the Cloudflow installer

Here is an example where the `Kafka` CR has TLS configured.
https://strimzi.io/docs/operators/master/using.html#ref-sample-kafka-resource-config-deployment-configuration-kafka

If you reconfigure this CR, Strimzi will reconfigure your Kafka cluster to use TLS.

The bootstrap server address and port the Cloudflow operator has been configured to use should stay the same.

### 2. Including certificates when building the Cloudflow application image

When building the Cloudflow application image, you can use the `extraDockerInstructions` task key in `build.sbt`, to add the TLS certificate files into the image, so they can be used by the Kafka client when the Cloudflow application starts.

Example:
```
  .settings(
    extraDockerInstructions := Vector(
      Instructions.Add(CopyFile(new File("/tmp/kafka.client.truststore.jks")), "/var/private/ssl/"),
      Instructions.Add(CopyFile(new File("/tmp/kafka.client.keystore.jks")), "/var/private/ssl/")
      ),
```

### 3. Adjusting the application configuration when deploying

It's not just enough to enable TLS on the Kafka cluster side, the Cloudflow application needs extra configuration to be able to use this.

Adding to the application configuration can be done using the new configuration system launched in 2.0.0

The configuration that needs to be modified when deploying a Cloudflow application is described here:
https://doc.akka.io/docs/alpakka-kafka/current/production.html#security-setup

```
akka.kafka.producer { # and akka.kafka.consumer respectively
  kafka-clients {
    security.protocol=SSL
    ssl.truststore.location=/var/private/ssl/kafka.client.truststore.jks
    ssl.truststore.password=test1234
    ssl.keystore.location=/var/private/ssl/kafka.client.keystore.jks
    ssl.keystore.password=test1234
    ssl.key.password=test1234
  }
}
```

Save this configuration into a file and use that file as extra configuration when deploying the application, like this:

`kubectl cloudflow deploy my-application.json --conf Kafka-client.conf`

For more information about the new configuration system in 2.0.x:
https://cloudflow.io/docs/current/develop/cloudflow-configuration.html

**Comment by jenoOvchi** [comment]
> https://cloudflow.io/docs/current/develop/cloudflow-configuration.html

Thats great!
Thank You!
It will be great to create in documentation new section about configuring the production environment including this steps and another important security things in Kafka, Akka, Spark and Flink.

**Comment by RayRoestenburg** [comment]
Cloudflow now does not depend on Strimzi anymore, you can now provide the details per topic, and https://github.com/lightbend/cloudflow/issues/685 will also support this for the default and named brokers. Closing this since it will be solved there.

**Comment by jenoOvchi** [comment]
Ok, Thanks!
