### ISSUE TITLE
Multiple SLF4J bindings on the classpath

### ISSUE THREAD

**Issue by olofwalker** [lightbend/cloudflow#617]
**Describe the bug**
Multiple SLF4J  bindings on the classpath. SLF4J does not bind to Logback classic for which we supply a `logback.xml` config file on the class path.

**To Reproduce**
Build a Cloudflow application and start it, any of the streamlet pods will print the following warnings:

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/cloudflow/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/cloudflow/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
```

**Expected behavior**
Logback classic is expected to be used.

**Additional context**
Until we provide a cleaned-up workaround for this, customers can use the following settings in their `build.sbt` to work around the issue.

```
.settings(
    useCoursier := false,
    excludeDependencies += "org.slf4j" % "slf4j-log4j12",
    excludeDependencies += "log4j"     % "log4j",
)
```

Note that `useCoursier := false` is needed until the fix for the following bug is published.
https://github.com/coursier/coursier/issues/1590

**Comment by olofwalker** [comment]
Local running specifically uses `log4j12`, so the above workaround does not work for local running. We need to standardize on either one of these and clean up the classpath.

**Comment by RayRoestenburg** [comment]
This has been solved by https://github.com/lightbend/cloudflow/pull/692.
