### ISSUE TITLE
Using semver to indicate patch releases

### ISSUE THREAD

**Issue by huntc** [lightbend/cloudflow#639]
Our customer has been caught out w.r.t. the implication of patch version numbers being used on releases where patch-style upgrades are not possible. Non-patch releases present a non-Business-As-Usual (BAU) situation requiring a medium to large scale organisation of people, whereas BAU releases are much easier to accommodate.

We should ensure that the version number of Cloudflow releases is in accordance with semver so that expectations are set correctly.

**Comment by thomasschoeftner** [comment]
This seems related to https://github.com/lightbend/cloudflow/issues/618 or at least could be covered with the same mechanisms, IMO.

**Comment by RayRoestenburg** [comment]
Can I close this @huntc ? this is basically an ongoing thing we have to check when releasing a version of Cloudflow. Re: #618 that is for building cloudflow applications, not for releasing Cloudflow.
