### ISSUE TITLE
As a user I want to be able to mount an existing secret as a volume.

### ISSUE THREAD

**Issue by olofwalker** [lightbend/cloudflow#648]
It would be very useful to be able to mount volumes using the config system. As a first step, we should make it possible to mount a secret as a volume. 

This is useful in the case when there are existing secrets on the cluster that you want to use.

**Comment by RayRoestenburg** [comment]
Something like:
```
    kubernetes.pods.pod {
      volumes {
        foo {
          secret {
            name = mysecret
          }
        }
      }

      containers.container {
        volume-mounts {
          name = foo
          mountPath = "/etc/my/file"
          readOnly = true
        }

```

**Comment by franciscolopezsancho** [comment]
Hey @RayRoestenburg , don't you think that is inconsistent with 
```
 env = [
    { 
       name = "JAVA_OPTS"
       value = "-XX:MaxRAMPercentage=40.0"
    },{
       name = "FOO"
       value = "BAR"
    }
   ]
```

**Comment by RayRoestenburg** [comment]
Maybe we can change the env later. Really prefer the hocon style. It is our own config, as you also said ;-)

**Comment by franciscolopezsancho** [comment]
:) cool. Sounds good 👍

**Comment by franciscolopezsancho** [comment]
as we need multiple volume-mounts I will read it like 
```
containers.container {
        volume-mounts {
          foo {
             mountPath = "/etc/my/file"
             readOnly = true
          },
          bar {
             mountPath = "/etc/my/file"
             readOnly = true
          }
        }
    }
```
would you agree? @RayRoestenburg

**Comment by RayRoestenburg** [comment]
The comma is not necessary in hocon @franciscolopezsancho

**Comment by RayRoestenburg** [comment]
I agree about the volume-mounts, then foo, bar, etc
