### ISSUE TITLE
Support for Avro payload compressed with Snappy

### ISSUE THREAD

**Issue by tringuyen-yw** [lightbend/cloudflow#652]
There is no support for Avro payload compressed with Snappy. 

Would appreciate it if Flink Streamlet could be considered with higher priority to have this feature.

**Comment by RayRoestenburg** [comment]
This should be possible by just setting snappy as compression type on the topic.

**Comment by RayRoestenburg** [comment]
@tringuyen-yw Would the above setting solve this issue?
