### ISSUE TITLE
akka.http.server.preview.enable-http2 by default

### ISSUE THREAD

**Issue by raboof** [lightbend/cloudflow#666]
**Is your feature request related to a problem? Please describe.**

Right now, to use gRPC, you must explicitly enable http2 in your configuration.

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**

Akka

**Describe the solution you'd like**

Cloudflow could enable http2 by default.

AFAICS right now cloudflow does not yet contain any 'default configuration' that deviates from the upstream `reference.conf`. If we would add this, I think we should also include something like Akka's `log-config-on-startup` to understand what the effective settings are and why.

**Comment by blublinsky** [comment]
Great feature
