### ISSUE TITLE
Move configuration of Kafka connection parameters from install time to deploy time.

### ISSUE THREAD

**Issue by olofwalker** [lightbend/cloudflow#669]
Currently, the Cloudflow operator is configured at install time with the Kafka connection parameters. This is not flexible and should be changed.

I propose the following change to improve the flexibility of this solution:

- The Kafka connection parameters are stored in a labeled secret together with a symbolic name, this can be done at install time for the conveniences of a default value, or at any other point in time.
- When deploying an application, the CLI will look for a Kafka connection secret with the same symbolic name as in the Blueprint.
- If no secret is found, the CLI will ask the user for the connection parameters and save those to a new secret.
- The CLI will use the symbolic name to refer to the connection parameters in the Cloudflow application CR.
- Utility functions could be added in the CLI to list, add, and remove secrets with Kafka connection parameters. This could be very convenient for the user, to get the right labels etc. on the secret.

**Comment by RayRoestenburg** [comment]
Now handled in #685.
