### ISSUE TITLE
`kubectl-cloudflow deploy` Give option to re-use or blank existing state

### ISSUE THREAD

**Issue by tringuyen-yw** [lightbend/cloudflow#673]
Using streamlet v2.0.7. When the same Cloudflow application is deployed (application name in `build.sbt` and streamlet name in `blueprint.conf` remain unchanged). The deployed streamlet re-uses the previous state saved in the checkpoint directory.

It would be convenient for `kubectl-cloudflow deploy` to allow the possibility to decide what to do with the previous state:

- re-use previous state (default behavior)
- blank previous state (ie. start the application like the very first deployment)

**Comment by RayRoestenburg** [comment]
Have you tried undeploy and then deploy again? I've done a small test and the PVC does get deleted when undeploy is used.

**Comment by jtownley** [comment]
I think this would open up room for mistakes to easily happen for now we recommend that you create a simple script for this procedure locally
