### ISSUE TITLE
Documentation and installer should try to minimize incorrect storage class choices during install

### ISSUE THREAD

**Issue by agemooij** [lightbend/cloudflow#68]
We have heard from various users that they have made incorrect choices for the RWO and RWM storage classes during installation, leading to performance problems (Kafka on NFS) or even broken installs (choosing a RWO class where a RWM is required).

This is made hard by the fact that unfortunately K8s doesn't seem to have an API for checking the RW capabilities of  a storage class (or the underlying provisioner. This seems to only be available at runtime when creating a PVC and it fails (at best) or succeeds when it should have failed (at worst).

The install script is trying to be as clear as possible by using some documented (in a public K8s docs page) provisioner capabilities but clearly this is not enough.

At least the docs and the install script should try to prevent as many problems as possible

cc: @nolangrace @blublinsky @lightbend/cloudflow-team

**Comment by RayRoestenburg** [comment]
https://github.com/lightbend/cloudflow/issues/709
