### ISSUE TITLE
Where is the repository for 2.1.0-SNAPSHOT? 

### ISSUE THREAD

**Issue by echang0929** [lightbend/cloudflow#684]
**Describe the bug**
For example sensor-data-scala, the file project/cloudflow-plugins.sbt includes configuration: 
`addSbtPlugin("com.lightbend.cloudflow" % "sbt-cloudflow" % "2.1.0-SNAPSHOT")`
but there is no repository which contains this version of package, so I got the error:

➜ sbt
[info] welcome to sbt 1.3.13 (Oracle Corporation Java 1.8.0_251)
[info] loading global plugins from /Users/timothyzhang/.sbt/1.0/plugins
[info] loading settings for project sensor-data-scala-build from plugins.sbt,cloudflow-plugins.sbt ...
[info] loading project definition from /Users/timothyzhang/MyProjs/Projs_Cloudflow/sensor-data-scala/project
[info] Updating
[info] Resolved  dependencies
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.lightbend.cloudflow:sbt-cloudflow:2.1.0-SNAPSHOT (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.lightbend.cloudflow:sbt-cloudflow;sbtVersion=1.0;scalaVersion=2.12:2.1.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/lightbend/cloudflow/sbt-cloudflow_2.12_1.0/2.1.0-SNAPSHOT/sbt-cloudflow-2.1.0-SNAPSHOT.pom
[error]   not found: /Users/timothyzhang/.ivy2/local/com.lightbend.cloudflow/sbt-cloudflow/scala_2.12/sbt_1.0/2.1.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.lightbend.cloudflow/sbt-cloudflow/scala_2.12/sbt_1.0/2.1.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.lightbend.cloudflow/sbt-cloudflow/scala_2.12/sbt_1.0/2.1.0-SNAPSHOT/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:218)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.lightbend.cloudflow:sbt-cloudflow;sbtVersion=1.0;scalaVersion=2.12:2.1.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/lightbend/cloudflow/sbt-cloudflow_2.12_1.0/2.1.0-SNAPSHOT/sbt-cloudflow-2.1.0-SNAPSHOT.pom
[error]   not found: /Users/timothyzhang/.ivy2/local/com.lightbend.cloudflow/sbt-cloudflow/scala_2.12/sbt_1.0/2.1.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.lightbend.cloudflow/sbt-cloudflow/scala_2.12/sbt_1.0/2.1.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.lightbend.cloudflow/sbt-cloudflow/scala_2.12/sbt_1.0/2.1.0-SNAPSHOT/ivys/ivy.xml

**Comment by RayRoestenburg** [comment]
Hi @echang0929 ,
We don't publish snapshots. You can build a snapshot from source if you like. The snapshots are used for CI and integration testing. Please use a released version: https://github.com/lightbend/cloudflow/releases/tag/v2.0.9

**Comment by echang0929** [comment]
Yes, I changed this configuration to 2.0.9: 

addSbtPlugin("com.lightbend.cloudflow" % "sbt-cloudflow" % "2.0.9")

Thanks.

**Comment by ennru** [comment]
Great that you got it to work.
Closing this issue.
