### ISSUE TITLE
Named Kafka cluster configurations for topic blueprint

### ISSUE THREAD

**Issue by seglo** [lightbend/cloudflow#685]
Kafka connection details can either be provided during installation (as simply, `bootstrap.servers`) or explicitly within a blueprint using advanced topic configuration.  In addition, we should let users define a reusable named Kafka connection configuration for as many clusters as they like.  The blueprint can then reference these configurations by a simple name.

A Kafka connection configuration will include the following information:

* name
* `bootstrap.servers` connection string
* producer client config
* consumer client config

During an application deployment the cloudflow operator will first lookup any referenced Kafka connection configurations and propagate them along to streamlets as they're created.

If a blueprint doesn't reference any Kafka cluster configurations then the current behaviour will be preserved. The order of precedence to load a configuration in this case will be:

* use the `default` Kafka cluster configuration, if it exists
* use the advanced connection info provided in the blueprint, if it exists
* use the `bootstrap.servers` configuration passed to the operator during install

Before deployment the CLI will verify that secrets containing any referenced Kafka cluster configurations exist.

**Comment by RayRoestenburg** [comment]
Looks like Robert did already write some things down in #669 maybe combine this @seglo.

**Comment by RayRoestenburg** [comment]
Would be nice, if you can set the TLS stuff in a shared connection config (not having to specify it as producer and consumer config) 

I would be fine with using hocon in the secret data  if that makes it easier.

**Comment by RayRoestenburg** [comment]
(the blueprint and config files already have support for these kind of settings, so maybe it makes sense for consistency to use the same/similar format)

**Comment by seglo** [comment]
> Would be nice, if you can set the TLS stuff in a shared connection config (not having to specify it as producer and consumer config)
> 
> I would be fine with using hocon in the secret data if that makes it easier.

Yes, I'm thinking about using a secret with a HOCON config file that uses the same config as in the blueprint.  We can update the chart to create a (`default`) if config is provided.  We can also use the chart to update the install with as many configs as we want, so the admin user doesn't have to figure out how to template and create the secrets themselves.

**Comment by RayRoestenburg** [comment]
That sounds great.

**Comment by seglo** [comment]
It looks like `helm` can't manage the creation of secrets. There's a [`helm-secrets`](https://github.com/zendesk/helm-secrets) plugin, but we don't want to saddle the user with installing that with helm.

I'll look into creating the secrets from the CLI as @olofwalker originally proposed in #669.

**Comment by RayRoestenburg** [comment]
@seglo it's just another resource? What goes wrong if you add a secret yaml file to the helm chart?

**Comment by RayRoestenburg** [comment]
@seglo Note that how the user distributes and encrypts their secret yaml, before using it for an install is out of scope for us. It is fine (especially for now) if the helm chart just takes an (no encrypted, normal) secret resource. Secret should use values, which user can set from environment variables, which they can keep secret (in CI etc).

**Comment by seglo** [comment]
My mistake.  Helm can create secrets, but I was getting tripped over the fact that it expects the `data` field to be base64.  Using the `stringData` field lets you provide non-encoded data.

**Comment by RayRoestenburg** [comment]
Some ideas for you to consider:
- The operator could set the App CR status to an error state explaining what is wrong (the named cluster does not exist, or no default found, etc). It's likely a lot easier to do this kind of validation on the operator side, of the fully merged config and the blueprint (because of hocon, and lack of full support on Golang side). It is of course more ideal for the CLI to prevent all problems before deployment, but it will at least provide feedback. The `kubectl cloudflow status` could also provide some more information about this specific issue.
