### ISSUE TITLE
Verify that the standard lyft/flinkk8soperator 0.5.0 works with Cloudflow.

### ISSUE THREAD

**Issue by RayRoestenburg** [lightbend/cloudflow#713]
It would be great if cloudflow works with a standard build of lyft Flink operator, for Flink 1.10. https://github.com/lyft/flinkk8soperator/releases/tag/v0.5.0

We're expecting that it does, it just has to be tested with our example applications.

**Comment by blublinsky** [comment]
Done, reflected in PR "Update Admin documentation" #716

**Comment by ennru** [comment]
#716 updated the docs to show how the Lyft Flink operator is used with Cloudflow.
