### ISSUE TITLE
Minimal retention periods for Streamzi Kafka

### ISSUE THREAD

**Issue by huntc** [lightbend/cloudflow#717]
Given the existing streamzi configuration defaults for Cloudflow, it is perhaps too easy for a Cloudflow deployment to crash given that Kafka does not handle running out of disk space gracefully. This was witnessed today with 2.0.10 in a customer's deployment.

Perhaps a better approach would be to specify minimal retention periods given the usage of Kafka as a message broker. Consider MQTT as a message broker where it will retain only the last published message. While Kafka offers more flexibility in this regard (retain as much as per the disk sizing), I feel we should configure its retention period per MQTT i.e. just the last published message. My feeling is that it is better for a user to realise that messages are being dropped than for Kafka (via streamzi) to crash.

**Comment by ennru** [comment]
The default retention policy for Cloudflow-managed topics can be set in the operator (must check how).
Strimzi is not involved in creating the Kafka topics anymore.

**Comment by RayRoestenburg** [comment]
That's a great point @ennru that I forgot about. The size for persistent volume etc, must be set in strimzi, if strimzi is used. Per topic configuration can be done through config files.

**Comment by RayRoestenburg** [comment]
The settings for strimzi that have been changed now just ensure defaults for the log size etc.

**Comment by RayRoestenburg** [comment]
Does this fix the issue https://github.com/lightbend/cloudflow/pull/719 @huntc ?
