### ISSUE TITLE
SBT Commands such as verifyBlueprint and runLocal seem to Depend on Git

### ISSUE THREAD

**Issue by ASRagab** [lightbend/cloudflow#72]
**Describe the bug**
I was trying to get started with the wind-turbine example, documented [here](https://cloudflow.io/docs/current/get-started/wind-turbine-example.html):
When attempting to run `runLocal` or `verifyBlueprint` from sbt shell, I received the following error
```sbt
[IJ]sbt:sensor-data> runLocal
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
Able to workaround by initializing git repository and providing initial commit.

**To Reproduce**
1. Create skeleton cloudflow project (insure plugin is enabled for project)
2. Do not initialize git repo
3. launch sbt interactively
4. run `verifyBlueprint` or `runLocal`

**Expected behavior**
It might not be unreasonable to require a git repository, given that source generation is part of the framework. However, perhaps as a gap in documentation or in the tutorial it could be added that this is also a requirement.

**Additional context**
From `gitter` and @agemooij:
`The first issue is caused by a feature of our SBT plugin, which will calculate a deterministicly unique version number for each image it produces. It appears our runLocal feature depends on this verison number while that is not strictly necessary. Feel free to report this as an issue!`

**Comment by olofwalker** [comment]
Thank you @ASRagab for taking the time to report this issue! We are aware that this is a kind of unexpected behavior/use of Git, even if we state in the docs that we require git. That is being said, we are moving away from this kind of verification soon, so I will go ahead and close this issue.
