### ISSUE TITLE
Add scalafmt and javafmt command as Akka

### ISSUE THREAD

**Issue by hepin1989** [lightbend/cloudflow#73]
I think that should be easy to copy from it?

**Comment by olofwalker** [comment]
Scalafmt has now been added, JavaFmt could be copied from for example the Akka project.

**Comment by osleonard** [comment]
I believe this should be closed @RayRoestenburg

**Comment by RayRoestenburg** [comment]
You are right @osleonard , closing it.

**Comment by RayRoestenburg** [comment]
Thanks for the contribution @osleonard!
