### ISSUE TITLE
shared a config in streamlet config-parameters: works for runLocal but failed when deployed on cluster

### ISSUE THREAD

**Issue by tringuyen-yw** [lightbend/cloudflow#731]
## OVERVIEW
This code sample is used to test how to share a config for multiple streamlets. The motivation for this test is to re-use a same set of config values for several streamlets. Therefore to avoid to copy/paste the same config values in every `cloudflow.streamlets.mystreamletABC.config-parameters`

The code is taken from Cloudflow example https://github.com/lightbend/cloudflow/tree/master/examples/snippets/modules/ROOT/examples/sensor-data-scala

The changes made to the original code:

- ./src/main/resources/local.conf (reproduced below): has some additional config param in particular the `common-creds` config block

- ValidMetricLogger.scala is modified to read those extra streamlet config params

```
cloudflow {
	streamlets {
		valid-logger {
			config-parameters = ${common-creds} {
			  log-level = "info"
			}
		}
 	}	
}

common-creds {
	bogus-username = "Default username (local.conf)"
	bogus-username = ${?BOGUSAPP_USER}
	bogus-password = "Default password (local.conf)"
	bogus-password = ${?BOGUSAPP_PWD}
}
```

## Prepare before running the test
Create the test environment varaibles in your terminal. Or in `.bashrc, .bash_profile, .zshrc` etc.

```
export BOGUSAPP_USER="Mr Spock"
export BOGUSAPP_PWD="Macchu Picchu"
echo "$BOGUSAPP_USER | $BOGUSAPP_PWD"
```

## RESULTS: OK on runLocal

`sbt runLocal` is able to acquire the config params values from shared config `common-creds` defined in `local.conf`, as shown in the runLocal logs:

```
[INFO] [14:59:12.470] ak.ac.ActorSystemImpl:99 ~~~ ValidMetricLogger acquiring config param values from environment vars:
    bogus-username: Mr Spock
    bogus-password: Macchu Picchu
```

## RESULTS: FAILED on Cluster

Deploy the app on the cluster. Notice the console output which already hints that `kubectl-cloudflow` plugin was unable to parse the shared config `common-creds` given in `--conf ./src/main/resources/local.conf`

```
kubectl cloudflow deploy ./target/sensor-data-scala.json --conf ./src/main/resources/local.conf


Default value 'Default from ValidMetricLogger.scala for param `bogus-password`' will be used for configuration parameter 'cloudflow.streamlets.valid-logger.config-parameters.bogus-password'
Default value 'Default from ValidMetricLogger.scala for param `bogus-username`' will be used for configuration parameter 'cloudflow.streamlets.valid-logger.config-parameters.bogus-username'
Default value 'valid-logger' will be used for configuration parameter 'cloudflow.streamlets.valid-logger.config-parameters.msg-prefix'
Please provide credentials for docker registry 'docker.io'.
The credentials will be stored in a Kubernetes image pull secret, so that the application can successfully be deployed.
```

And indeed, the pods logs confirm that the streamlet could not read the config param from `local.conf`. The default values hardcoded in the streamlet were used. The test failed when the syntax `valid-logger = ${common-creds}` is used. The content inside the `common-creds` config block is irrelevant.

```
kubectl logs sensor-data-scala-valid-logger-5cc4c949d-szqck -n sensor-data-scala

2020-09-15 19:17:10,934 1271 [INFO ] [valid-logger-akka.actor.default-dispatcher-5] a.a.ActorSystemImpl a.e.s.Slf4jLogger$$anonfun$receive$1.$anonfun$applyOrElse$3 (Slf4jLogger.scala:96) – ~~~ ValidMetricLogger acquiring config param values from environment vars:
    bogus-username: Default from ValidMetricLogger.scala for param `bogus-username`
    bogus-password: Default from ValidMetricLogger.scala for param `bogus-password`
```

## RESULTS: Cluster OK if shared config is NOT used

Suppressing the `valid-logger = ${common-creds}` syntax in `local.conf` solves the pb (which then defeats the goal of sharing config). Modify the config as `local2.conf` as below and redeploy the app on tne cluster. Notice the console output of `kubectl cloudflow deploy` no longer complain about `bogus-username` and `bogus-password` params  

```
cloudflow {
	streamlets {
		valid-logger {
			config-parameters {
			  log-level = "info"

        bogus-username = "Default username (local.conf)"
        bogus-username = ${?BOGUSAPP_USER}
        bogus-password = "Default password (local.conf)"
        bogus-password = ${?BOGUSAPP_PWD}
			}
		}
 	}	
}


kubectl cloudflow deploy ./target/sensor-data-scala.json --conf ./src/main/resources/local2.conf

Default value 'valid-logger' will be used for configuration parameter 'cloudflow.streamlets.valid-logger.config-parameters.msg-prefix'
Please provide credentials for docker registry 'docker.io'.
The credentials will be stored in a Kubernetes image pull secret, so that the application can successfully be deployed.
```

The pod logs show 

- the streamlet has been able to read param value from `local.conf`

- HOWEVER the config values are no longer substituted from environment variables (defined on the machine where `kubectl cloudflow deploy` was executed). Which means that the HOCON technique of env var substitution doesn't work with `kubectl cloudflow deploy` 

```
kubectl logs sensor-data-scala-valid-logger-5cc4c949d-xs64c -n sensor-data-scala

2020-09-15 19:22:43,140 1248 [INFO ][valid-logger-akka.actor.default-dispatcher-4].a.ActorSystemImpla.e.s.Slf4jLogger$$anonfun$receive$1.$anonfun$applyOrElse$3(Slf4jLogger.scala:96)– ~~~ ValidMetricLogger acquiring config param values from environment vars:
    bogus-username: Default username (local.conf)
    bogus-password: Default password (local.conf)

```

(end)

**Comment by RayRoestenburg** [comment]
[SensorData_SharedConfig.zip](https://github.com/lightbend/cloudflow/files/5275344/SensorData_SharedConfig.zip)

**Comment by RayRoestenburg** [comment]
@tringuyen-yw I have found the reason for this not working at the moment. the kubectl cloudflow plugin has limited support for parsing HOCON at this time, and does not support this syntax, so it incorrectly detects that the config-parameters are not provided, and since these have defaults, it uses the defaults.

**Comment by RayRoestenburg** [comment]
@franciscolopezsancho Can we close this, and explain not to use the ${reuse_hocon_object} in config-parameters?

**Comment by tringuyen-yw** [comment]
Would like to add some weight to bump this feature request to higher priority. The inability of shareing config causes a significant burden in deployment. Especially when devops team (who deploys) is not member in dev team (who create the config).

We just went through a deployment of 5 pipelines (5 blueprints). Each pipeline has 2 streamlets. There are 4 deployment environments. The same shared config block is copied 5 * 2 * 4 = 40 times.

The pipelines are not yet stabilized so those config need to be changed often. So far at each release, someone ALWAYS made a mistake to copy/paste those config. Myself included! Just did yesterday, I carefully checked everything. And yet I still made a mistake: forgot to update the streamlet name when copy over the config of another streamlet.

**Comment by RayRoestenburg** [comment]
@andreaTP I think with the new cli, this will work OOTB? can we close this?

**Comment by andreaTP** [comment]
yes, since Cloudflow 2.0.20 there is no limitation in using the full HOCON config.

**Comment by RayRoestenburg** [comment]
@tringuyen-yw ☝️

**Comment by tringuyen-yw** [comment]
Wonderful, thanks very much guys.

**Comment by akandach** [comment]
cloudflow {
  streamlets {
    ingress {
      config-parameters {
        consumer {
          eventhub {
            bootstrap.servers = "#{INGRESS_EVENTHUB_BOOTSTRAP_SERVER}#"
            group.id = "#{INGRESS_GROUP_ID}#"
            sasl.mechanism = "#{SASL_MECHANISM}#"
            security.protocol = "#{SECURITY_PROTOCOL}#"
            sasl.jaas.config = "#{INGRESS_SASL_JAAS_CONFIG}#"

          }
          kafka {
            bootstrap.servers = "#{INGRESS_KAFKA_BOOTSTRAP_SERVER}#"
            group.id = "#{INGRESS_GROUP_ID}#"
          }
        }
        keyvault {
          name = "#{KEYVAULT_NAME}#"
          clientid = "#{KEYVAULT_CLIENT_ID}#"
          clientsecret = "#{KEYVAULT_CLIENT_SECRET}#"
          sharedaccesskey = "#{INGRES_SHARED_ACCESS_KEY}#"
        }
        service-name = "#{SERVICE_NAME}#"
        service-suffix = "#{SERVICE_SUFFIX}#"
        message-broker = "#{MESSAGE_BROKER}#" #Valid values: "eventhub", "kafka"
        topic = "#{INGRESS_TOPIC}#"
        #topic = "ev-app-a00ad3-dptransformationingress"
      }
    }
  }
}

in some environments it is working but in some environment we are getting the below error 
Unknown config parameter 'producer'
