### ISSUE TITLE
Latest version of kubectl cloudflow is broken

### ISSUE THREAD

**Issue by blublinsky** [lightbend/cloudflow#766]
**Describe the bug**
When using a latest version of kubectl cloudflow - kubectl-cloudflow-2.0.11-RC2.757-8ba09490-darwin-amd64.tar.gz you always need to specify config (even if it empty). For example:

cloudflow.runtimes.flink.config {}

Also, there is a new undocumented feature --no-registry-credentials flag, which is great, but not documented

**To Reproduce**
If you try to deploy a pipeline without configuration, you will see an error:

[Error] Configuration misses root 'cloudflow' section

**Expected behavior**
Configuration should not be required

**Additional context**
--no-registry-credentials flag should be documented

**Comment by RayRoestenburg** [comment]
Cannot reproduce
