### ISSUE TITLE
Build cloudflow base images from upstream generic images

### ISSUE THREAD

**Issue by andreaTP** [lightbend/cloudflow#782]
**Is your feature request related to a problem? Please describe.**
Currently to build a Cloudflow application we need to have a specific base image uploaded matching version of Scala, Akka, Cloudflow itself, and more.
This is not strictly required e.g. the base image:
```
lightbend/akka-base:2.0.10-cloudflow-akka-2.6.9-scala-2.12
```
doesn't rely on any specific version of Akka, Scala and has very little to do with Cloudflow specifics as well:
https://hub.docker.com/layers/lightbend/akka-base/2.0.10-cloudflow-akka-2.6.9-scala-2.12/images/sha256-5f418d005be362cf847db272b66a7a83c2e7032c54ec36099d2a0b5671e35363?context=explore

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
All runtimes.

**Describe the solution you'd like**
The build of Cloudflow applications can be self-contained in the Sbt plugin depending on upstream base images.

**Comment by RayRoestenburg** [comment]
@andreaTP I think this can be closed.

**Comment by andreaTP** [comment]
yes! 🎉
