### ISSUE TITLE
Defining config params unknown to Kafka crashes the cloudflow-operator

### ISSUE THREAD

**Issue by thomasschoeftner** [lightbend/cloudflow#794]
**Describe the bug**
When passing config parameters unknown to Kafka in the `topics` section of a blueprint topic definition, makes the cloudflow-operator continuously crash with an exception: `org.apache.kafka.common.errors.InvalidConfigurationException: Unknown topic config name: partitions`.

**To Reproduce**
Deploy a blueprint using an erroneous topic config.
Example:
```
blueprint {
  streamlets { ... }

  topics {
    mytopic = ${advanced-topic-config} {
      producers = [...]
      consumers = [...]
    }
  }
}

advanced-topic-config {
  topic {
    retention.ms = 123321  # config key from Kafka docs
    replicas = 4           # known config key in Cloudflow blueprint
    partitions = 13        # known config key in Cloudflow blueprint
  }
}
```

**Expected behavior**
IMO, the cloudflow-operator should
- not crash
- log an error
- stop trying to deploy the application with the faulty blueprint

**Screenshots**
n/a

**Additional context**
Things surfaced during [this thread on gitter](https://gitter.im/lightbend/cloudflow?at=5f7321f95efe9467b1230301).

**Comment by thomasschoeftner** [comment]
I should add, that this did NOT happen in 2.0.7, but is reproducible in 2.0.10

**Comment by RayRoestenburg** [comment]
This issue is similar to #603 since the operator should handle exceptions that occur when creating topics.
