### ISSUE TITLE
Upgrade to Akka 2.6.x

### ISSUE THREAD

**Issue by RayRoestenburg** [lightbend/cloudflow#80]
**Is your feature request related to a problem? Please describe.**
Upgrading to Akka 2.6.x 

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
Akka

**Describe the solution you'd like**
Upgrade dependencies on Akka to version 2.6.x

**Comment by yuchaoran2011** [comment]
Blocked by Flink's dependency on Akka 2.5.
