### ISSUE TITLE
Make it possible to set jobmanager and taskmanager settings through flink config (configuration model)

### ISSUE THREAD

**Issue by RayRoestenburg** [lightbend/cloudflow#813]
**Is your feature request related to a problem? Please describe.**
A user requested to be able to set taskmanager taskSlots, which is now configured in cloudflow operator settings.
https://gitter.im/lightbend/cloudflow?at=5f8ed9a87be0d67d2785b2dc

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
Flink.

**Describe the solution you'd like**
For it to be possible to set taskSlots, but also other settings, for the jobmanager and taskmanager.
It might be possible to set taskSlots with `taskmanager.numberOfTaskSlots`, but this has not been tested yet. We should also look at all the other settings that are now in cloudflow operator application.conf for jobmanager and taskmanager.

**Comment by Lockdain** [comment]
Guess the feature is somehow related to the #497 
The most desirable parameters to config are:

1. [parallelism](https://github.com/lightbend/cloudflow/blob/master/core/cloudflow-operator/src/main/resources/application.conf#L106)
2. [task-slots](https://github.com/lightbend/cloudflow/blob/master/core/cloudflow-operator/src/main/resources/application.conf#L132)
3. [replicas](https://github.com/lightbend/cloudflow/blob/master/core/cloudflow-operator/src/main/resources/application.conf#L108)

The first and the second are needed to calculate a total quantity of task manager to be deployed, the third one possibly relates to the job manager HA-mode.

**Comment by RayRoestenburg** [comment]
Thanks @Lockdain we'll make sure to make those configurable.

**Comment by RayRoestenburg** [comment]
Please see https://github.com/lightbend/cloudflow/commit/a78e332def6d9fa0381416a92b9ee3a7e74b7c66, I think this should do the trick.

**Comment by RayRoestenburg** [comment]
You can now set the `parallelism.default` and `taskmanager.numberOfTaskSlots`. We added a `jobmanager.replicas` that can be set in flink.config, though it is not part of the flink configuration, which you could try for HA setup.
