### ISSUE TITLE
Investigate Google Flink Operator.

### ISSUE THREAD

**Issue by RayRoestenburg** [lightbend/cloudflow#815]
Spike to see how good the Google Flink Operator is currently.

**Comment by Lockdain** [comment]
Hi @RayRoestenburg 
I've noticed the issue and read some issues at the Lyft repo opened by Lightbend almost a year ago.
So I wonder why did you prefer the Lyft Flink operator over Google?

**Comment by RayRoestenburg** [comment]
I think at the time the Lyft Flink operator was further ahead than the one by Google. That might have changed. @debasishg do you remember?

**Comment by Lockdain** [comment]
I've slightly checked the current Flink operator from Google documentation, seems that it didn't make any notable progress for the last year.

**Comment by blublinsky** [comment]
Here is some comparison of operators http://apache-flink-user-mailing-list-archive.2336050.n4.nabble.com/Difference-between-flink-on-kubernetes-operator-vs-native-kubernetes-td36104.html - not much, but something.
In Flink 1.11 there is a new option - flink native https://ci.apache.org/projects/flink/flink-docs-stable/ops/deployment/native_kubernetes.html. 
This can alleviate the need for Flink operator. We need more testing, but from the look of it cloudflow operator can use this directly to start Flink jobs. https://ci.apache.org/projects/flink/flink-docs-release-1.11/ops/deployment/native_kubernetes.html#flink-kubernetes-application. We need some experimentation to see how checkpointing and scaling behaves, but in general this looks like a great option

**Comment by RayRoestenburg** [comment]
Closing this ticket, it seems more interesting to look at 1.12 native k8s support.
