### ISSUE TITLE
Ability to add javaagents to Cloudflow pods and configure them explicitly

### ISSUE THREAD

**Issue by thomasschoeftner** [lightbend/cloudflow#820]
**Is your feature request related to a problem? Please describe.**
With Cloudflow 2.0.11 it is very hard to expose custom application metrics (e.g. based on Prometheus client libs) to the metrics backend, because:
- The integrated jmx-exporter is not configurable from the outside to expose custom metrics
- It is not possible to add and configure extra javaagents
- Running another off-the-shelf endpoint exposing metrics for scraping is not possible, because presently Cloudflow does not allow to configure port-mappings, so the extra HTTP endpoint for metrics scraping cannot be exposed.

The remaining alternatives seem to be:
- Modify the base container image used for running Streamlets (tought to maintain, error-prone, not flexible)
- Use Push-Gateways to emit metrics actively from code.

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
We have seen this problem with AkkaStreamlets up to version 2.0.11.
It is likely that the same limitation also holds for Flink- and SparkStreamlets.

**Describe the solution you'd like**
- Ability to define extra java-agents to be run
- Ability to configure any java-agents
- Ability to explicitly configure exposed ports (works as a powerful fallback for many similar problems)

**Describe alternatives you've considered**
Actively emitting data instead of exposing it via (HTTP) endpoints

**Additional context**
n/a

**Comment by RayRoestenburg** [comment]
This is now possible, you can add java agents to JAVA_OPTS. Container ports (https://cloudflow.io/docs/current/develop/cloudflow-configuration-kubernetes.html#_container_ports) and annotations (https://cloudflow.io/docs/current/develop/cloudflow-configuration-kubernetes.html#_annotations) are now configurable.
In the lightbend docs there is an example of setting up another java agent (https://developer.lightbend.com/docs/cloudflow/current/console/setting-up-monitoring.html)
Do you think we can close this now @thomasschoeftner ?

**Comment by thomasschoeftner** [comment]
awesome - thank you!
