### ISSUE TITLE
Migrate to Helm for Cloudflow update delivery

### ISSUE THREAD

**Issue by jenoOvchi** [lightbend/cloudflow#824]
**Is your feature request related to a problem? Please describe.**
Cloudflow project build and deploy tool is very specific and not suitable for continuous delivery (you can't build, push and deploy to different environments separately and without a lot of "sed").

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
All runtimes.

**Describe the solution you'd like**
It will be great to modify Cloudflow build and deploy process to create set of images and Helm Chart and add commands to push it to external registries.

**Describe alternatives you've considered**
Add functions to build, push and deploy to different environments separately and without a lot of "sed".

**Additional context**
No.

**Comment by andreaTP** [comment]
Can you elaborate a little more describing your real use-case scenario?
Multiple docker registries? Multiple clusters? Something else?

**Comment by jenoOvchi** [comment]
> Can you elaborate a little more describing your real use-case scenario?
> Multiple docker registries? Multiple clusters? Something else?

Yes - for example if we work with two different OpenShift clusters we need to push images to two different Docker Registries and fix image names in project Cloudflow config file for the second cluster. And it is only one case.

**Comment by RayRoestenburg** [comment]
> you can't build, push and deploy to different environments separately and without a lot of "sed"

It *is* possible to push and deploy to different environments, as long as those environments use the *same* docker registry. This might not be the right assumption for everyone. Configuration files can be used to provide environment specific settings, when using `kubectl cloudflow deploy`.

So I'm assuming this issue is really about pushing images to different docker registries? I'm assuming you would not need to push to different docker registries for the same application? 

The `sbt buildApp` command both builds and pushes the images, only if `cloudflowDockerRegistry` sbt setting is set. If it is not set, sbt buildApp builds the images locally,  and the CR refers to the image refs, as built, without a repository reference. 

You could run sbt from CI in this way, to push to many registries (by repeating the below line for different registry and repo):
```sbt 'set ThisBuild / cloudflowDockerRegistry := Some("$MY_DOCKER_REGISTRY");set ThisBuild / cloudflowDockerRepository := Some("$MY_DOCKER_REPO"); buildApp'```
And then deploy with `kubectl cloudflow deploy some-cr.json`
Would that work for you?

**Comment by andreaTP** [comment]
Thanks a lot for your comment @jenoOvchi !
We recently introduced a mechanism for decoupling the image versions from their `sha`.
What you need to do is omit `cloudflowDockerRegistry` or(equivalent):
```scala
cloudflowDockerRegistry := None
```
at this point, the CR file will be generated respecting the `version` key in your project, and the image is not being pushed to the docker registry.

You can automate a little your build with something like:
```scala
val myRegistry = settingKey[String]("Name of the docker registry")
myRegistry := "default"
cloudflowDockerImageName := Some(cloudflow.sbt.DockerImageName(s"${myRegistry.value}/${(ThisProject / name).value}", (ThisProject / version).value))
```
and run:
```
sbt 'set myRegistry := "my-registry1"; buildApp'
docker push my-registry1/<proj-name>:version
kubectl cloudflow deploy deploy target/<proj-name>.json

sbt 'set myRegistry := "my-registry2"; buildApp'
docker push my-registry2/<proj-name>:version
kubectl cloudflow deploy deploy target/<proj-name>.json
```

you can test this functionality using a nightly release (e.g. `2.0.11-26102020`)
Let me know if this works for you.

**Comment by jenoOvchi** [comment]
> Thanks a lot for your comment @jenoOvchi !
> We recently introduced a mechanism for decoupling the image versions from their `sha`.
> What you need to do is omit `cloudflowDockerRegistry` or(equivalent):
> 
> ```scala
> cloudflowDockerRegistry := None
> ```
> 
> at this point, the CR file will be generated respecting the `version` key in your project, and the image is not being pushed to the docker registry.
> 
> You can automate a little your build with something like:
> 
> ```scala
> val myRegistry = settingKey[String]("Name of the docker registry")
> myRegistry := "default"
> cloudflowDockerImageName := Some(cloudflow.sbt.DockerImageName(s"${myRegistry.value}/${(ThisProject / name).value}", (ThisProject / version).value))
> ```
> 
> and run:
> 
> ```
> sbt 'set myRegistry := "my-registry1"; buildApp'
> docker push my-registry1/<proj-name>:version
> kubectl cloudflow deploy deploy target/<proj-name>.json
> 
> sbt 'set myRegistry := "my-registry2"; buildApp'
> docker push my-registry2/<proj-name>:version
> kubectl cloudflow deploy deploy target/<proj-name>.json
> ```
> 
> you can test this functionality using a nightly release (e.g. `2.0.11-26102020`)
> Let me know if this works for you.

Ok, thanks!
Now we run on 2.0.5, i think we will test it on release 2.0.12.
But I think it is workaround and deploy it with helm will be more flexible and standartised.

**Comment by jenoOvchi** [comment]
Hi!
Are you plan to migrate to Helm? Or is it possible to use GitOps practics to deploy Cloudflow now?

**Comment by andreaTP** [comment]
Hi @jenoOvchi !
Thanks for reaching out!

There are currently no plans to move to Helm, currently, the Cli gives our users an immense value providing very accurate validation of the input (CR specifications/configuration) and doing checks against the cluster as well.

This cannot be replicated easily with Helm templates.

I close this Issue and, please, feel free to open another one for any specific need you have!
