### ISSUE TITLE
Stoppers registered in onStop for AkkaStreamlets are not always called

### ISSUE THREAD

**Issue by orElse** [lightbend/cloudflow#849]
**Describe the bug**
Stoppers are currently only called when the stop is explicitly called - they should always be called if the AkkaStreamlet completes 
see https://cloudflow.zulipchat.com/#narrow/stream/263236-cloudflow/topic/shutdown.20behaviour.20for.20Akka.20Streamlet/near/215576055

**To Reproduce**
Register a stopper in an AkkaStreamlet and stop the streamlet by other means than calling stop method (e.g. deploy, restart pod, ...)

**Expected behavior**
Registered stoppers should always be called if a AkkaStreamlet completes 

**Screenshots**

**Additional context**

**Comment by ennru** [comment]
This is addressed in #853 which makes use of Akka Coordinated shutdown to trigger `stop`.

**Comment by ennru** [comment]
Fixed with #853
