### ISSUE TITLE
Is it possible to use Apache Pulsar instead of Apache Kafka

### ISSUE THREAD

**Issue by NicolasRouquette** [lightbend/cloudflow#869]
**Is your feature request related to a problem? Please describe.**

At Scale By The Bay 2020, Karthik Ramasamy gave a keynote presentation about Apache Pulsar at Splunk.
He showed benchmark results that show a very compelling case for using Pulsar instead of Kafka.

At Nolan Grace's presentation about Cloudflow, I wondered weather it is possible to replace Kafka with Pulsar in Cloudflow.

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
Some feature requests may be relevant only for specific runtimes. Please describe in details.

**Describe the solution you'd like**

It may be possible to use the Pulsar adapter for Kafka to facilitate the switch:

https://pulsar.apache.org/docs/en/adaptors-kafka/

**Describe alternatives you've considered**

**Additional context**

**Comment by RayRoestenburg** [comment]
Sorry for the late response. Right now Cloudflow does not work with Pulsar. We have not tried the Pulsar adapter for Kafka. Skimming over the docs it looks like it means that Flink, Spark and Akka Cloudflow libs would have to replace dependency on kafka-client. We don't use the kafka-client directly in Cloudflow, but through alpakka kafka in the case of Akka streamlet library, and through Spark and Flink API's respectively for Spark and Flink streamlet libraries. It might be possible to do this  though, theoretically.
