### ISSUE TITLE
Add an option to add trigger.continuous to Sparklet

### ISSUE THREAD

**Issue by blublinsky** [lightbend/cloudflow#89]
**Is your feature request related to a problem? Please describe.**
For simple queries trigger.continuous allows to produce results continuously, not as mini batch. This allows for faster processing in Sparklets putting them on par with Akka streams and Flink

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
Only relevant for Spark runtime

**Describe the solution you'd like**
I would like to allow to specify trigger option for Spark query

**Describe alternatives you've considered**
There are none

**Additional context**
None

**Comment by olofwalker** [comment]
@blublinsky We are working on improving the way configuration of streamlets, runners, etc is done, once this have been completed, this should be possible to achieve using that new system.
