### ISSUE TITLE
Error Handling for non-existing files or malformed content

### ISSUE THREAD

**Issue by sebastian-alfers** [lightbend/cloudflow#898]
Error handling for non-existing files or malformed content could be improved.

**Comment by RayRoestenburg** [comment]
https://github.com/lightbend/cloudflow/pull/889

**Comment by sebastian-alfers** [comment]
Thanks @RayRoestenburg Is there a planned release this feature will be in?

**Comment by RayRoestenburg** [comment]
It will be in the next release, possibly this week.

**Comment by andreaTP** [comment]
Merged and released in `2.0.19`
