### ISSUE TITLE
Document strimzi for development usage only

### ISSUE THREAD

**Issue by huntc** [lightbend/cloudflow#918]
I think we should recommend that strimzi should only be used in non-production scenarios. Aside from being complex to manage, I've long operated on the principle that persistent storage should be managed outside of an orchestrator. The reason for this is mostly down to the consequences of rebalancing data nodes in an environment that is dynamic. However, persistent storage often needs to be treated like "pets", not "cattle" i.e. one's data needs to be looked after.

**Comment by andreaTP** [comment]
Completely agree, followed up in #920 
Feel free to suggest a different wording @huntc ! :-)
