### ISSUE TITLE
Documentation site incosistencies

### ISSUE THREAD

**Issue by andreaTP** [lightbend/cloudflow#937]
cloudflow.io after the new update has a few rough edges:

 - links from the search bar redirect always to `dev`
 - the `version selection` menu (bottom left) shows content that is not intended to be shown (e.g. `docsnippets`, `shared-content`, `master Beta`)
 - I "think" it was decided to remove the link `Edit this page`

the added value of the search bar outweigh those small issues, so I keep it for this Christmas break 🙂 

Can you @rstento / @rasummer help in solving this?

**Comment by RayRoestenburg** [comment]
@andreaTP all of this has been resolved, closing this, reopen please if you disagree.
