### ISSUE TITLE
Bash restriction breaks installer usage with Zsh

### ISSUE THREAD

**Issue by mrooding** [lightbend/cloudflow#94]
**Describe the bug**
Commit 67eb5e0 introduces a requirement on bash >= 4 based on a `BASH_VERSINFO` env var for running the GKE installer. However, when using other shells, like Zsh on MacOS, it fails to meet the requirements due to `BASH_VERSINFO` not being set.

**To Reproduce**
Run `./install-gke.sh <cluster_name>` with Zsh (https://ohmyz.sh/)

**Expected behavior**
Allow the installer to run with multiple shells.

**Screenshots**

**Additional context**

**Comment by debasishg** [comment]
Currently we have the bash version documented as a prerequisite (https://developer.lightbend.com/docs/cloudflow/current/install/prerequisites.html). So in case u r using zsh, you need to run bash first. May be this will change in future ..

**Comment by skyluc** [comment]
@mrooding Can you give some more information on how it is failing?

The `install-gke.sh` script starts with
```
#!/usr/bin/env bash
```
Is this directive not taken in account by Zsh ?

----
In fact, thinking about this, the problem you see might be with the version of bash installed on your system, no the fact that you are running Zsh.
By default, MacOS only has a really old version of bash installed. Installing a newer version of bash (available through `brew`) should fix your problem.

**Comment by mrooding** [comment]
@skyluc You were indeed correct. The shebang was being used properly but it was using the built-in bash 3.2. Installing bash with brew did the trick. Apologies for the confusion!
