### ISSUE TITLE
Add prometheus.io/port annotation to deployments 

### ISSUE THREAD

**Issue by orElse** [lightbend/cloudflow#950]
**Is your feature request related to a problem? Please describe.**
Currently only the 'prometheus.io/scrape' annotation is set this means for HTTPStreamlets also the second port will be scraped - this leads to scrape target down alerts for our setup.

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**

**Describe the solution you'd like**
The 'prometheus.io/port' annotation is set to the jmx agent port

**Describe alternatives you've considered**
setting the annotation for all pods with an additional config file during deployment - otherwise we would have to provide a metrics endpoint for all HTTP streamlets

**Additional context**

**Comment by RayRoestenburg** [comment]
Hi @orElse, version 2.0.22 is coming out soon, which has support for adding annotations through the configuration file. Would that work?

**Comment by orElse** [comment]
@RayRoestenburg since we currently have to add some additional common config to all our deployments anyway this should probably work for us

**Comment by RayRoestenburg** [comment]
FYI in 2.0.22 it is also possible to add container ports through config.

**Comment by orElse** [comment]
thanks good to know - will help us in the future

**Comment by RayRoestenburg** [comment]
2.0.22 is released, so closing this ticket.
