### ISSUE TITLE
Support for FS2

### ISSUE THREAD

**Issue by pascals-ager** [lightbend/cloudflow#98]
This is a very selfish feature request. I have been using the Scala library FS2 and have come to absolutely love it. Meanwhile I also see the value of Frameworks like Cloudflow. So here is me hoping the team considers providing support for FS2 in the cloudflow ecosystem.

**Comment by olofwalker** [comment]
@pascals-ager Thank you very much for your interest in Cloudflow. We have discussed this in the team and right now we will prioritize work in the roadmap that makes it easier in the future to add new runners (like for example FS2). We will close the issue for now but may revisit it later.
