### ISSUE TITLE
the new "Download and install the Cloudflow CLI" process fails on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by michael-read** [lightbend/cloudflow#988]
**Describe the bug**
The Cloudflow CLI official installer fails on Ubuntu 16.04 LTS.

Also typo for download, "If the installer script fails (e.g. there is no curl nor wget installed) **downaload** the binaries at the specific version from:"

Sadly, I wasn't able to figure out how to download the specific version either from the link below:
https://bintray.com/lightbend/cloudflow-cli/kubectl-cloudflow

**To Reproduce**
curl -sL http://cloudflow.io/docs/get.sh | sh
sh: 14: set: Illegal option -o pipefail
(23) Failed writing body

Note: I have *curl* and *wget* installed.

**Comment by RayRoestenburg** [comment]
Is this maybe a shell issue? 
> Ubuntu sh is linked to dash not bash. pipefail is a bash utility.
Can you try again with 
```
curl -sL http://cloudflow.io/docs/get.sh | bash
```
Just to see what happens..

**Comment by RayRoestenburg** [comment]
@andreaTP
