### ISSUE TITLE
Remove the need for the CF-operator to run as root.

### ISSUE THREAD

**Issue by michael-read** [lightbend/cloudflow#997]
**Is your feature request related to a problem? Please describe.**
When organizations don't trust anyone or anything on their network they want to lock down everything. 

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
Just the Cloudflow operator.

**Describe the solution you'd like**
run the operator as a user instead of root.

**Comment by andreaTP** [comment]
Fixed in #994

**Comment by sebastian-alfers** [comment]
@andreaTP Was this also released?

**Comment by andreaTP** [comment]
@sebastian-alfers yes `2.0.25`
